# 摘要

::: {.content-hidden when-format="pdf"}

## 從消費者到投資者的旅程：為年輕成人設計一個財務人工智慧夥伴，幫助他們進行可持續購物、儲蓄和投資

:::

台灣的年輕人，特別是大學生，關注環境問題，但因缺乏簡單的工具來影響系統性改變而受阻。同時，歐盟加強的環保政策引入了「數字產品護照」的概念，旨在區分由努力實現零廢棄的「循環經濟」公司製造的「生態設計」產品，與僅從事「漂綠」的公司。從原料開始追蹤產品數據，直到消費者的購買決策，最後到購後的回收，促進在不透明的全球供應鏈中建立透明度。 「數據驅動的互動設計」、「大型語言模型」和「人工智慧助理」將復雜的環境數據轉換成人類可理解的語言。

新興的「地球健康」領域認識到，我們的經濟行為、生態系統服務（如清潔的水、空氣、土壤）、氣候危機和人類健康之間存在著深刻的相互聯繫。截至2024年，由於生產我們日常購買的許多產品和服務的公司進行的開採性商業行為，地球的自然環境正被嚴重破壞。我們用金錢與公司互動的方式——作為消費者的購物和作為投資者的儲蓄/投資——對我們賴以維持地球宜居性的生命支持生物圈產生影響。從生態學角度來看，每一個財務行動不是支持更環保公司的投資決策，就是支持污染者。透過民主化金融市場，年輕人可以獲得更大的權限和影響力，控制他們的資金流向，使他們能夠支持可持續和對環境負責的公司。

我的研究針對了需要工具來使可持續的財務行動更便捷的需求，特別關注大學生。我利用設計研究來尋找簡單的基於AI的使用者介面的設計概念，也稱為生成式UI，以幫助年輕人參與可持續的財務行動主義。在台灣10所大學進行了涵蓋700名學生的調查，並透過5次專家訪談提供行業見解。研究的主要貢獻是一個互動式AI助理原型。

關鍵詞：人機互動、數字可持續性、透明度

*The abstract was translated on May 22, 2024 using the Claude 3 Opus model. Translation quality was checked with OpenAI GPT4, Google Gemini, Mistral Large, Meta LLama, as well as human reviewers, and further refined with the OpenAI o1-preview model in November 2024. In case of any discrepancies, please refer to the English text.*