# Abstract

::: {.content-hidden when-format="pdf"}
## The Journey from Consumer to Investor: Designing a Financial AI Companion for Young Adults to Help With Sustainable Shopping, Saving, and Investing
:::

As of 2025, Earth's natural environment is being heavily degraded by the extractive business practices of companies that make many of the products and services we buy every day. The emerging field of *planetary health* recognizes profound interconnections between our economic behaviors, ecosystem services such as clean water, air, soil, the climate crisis, and human health. The way we use our money to interact with companies - through shopping as consumers and saving / investing as investors - has an effect on the life-supporting biosphere we rely on to keep our planet inhabitable. In essence, from an ecological perspective, every financial action is either an investment decision to support more environmentally-friendly companies - or to support polluters. By democratizing financial markets, young adults can gain greater access and influence over where their money goes, enabling them to support sustainable and environmentally responsible companies.

In Taiwan, college students are concerned with environmental issues, yet face an *attitude-behavior gap* and lack simple tools to effectively influence systemic change towards sustainable outcomes. Concurrently, in the European Union, new environmental policies promote *digital product passports*, aiming to distinguish *eco-designed products* made by circular economy companies, striving to be *zero waste*, from those merely engaged in *greenwashing*. Tracking complex environmental data from products' source materials, until the consumer purchase decision, and finally post-purchase recycling, facilitates building *transparency* into opaque global supply chains, which *data-driven interaction design*, *large-language models*, and *AI agents* can translate into human-comprehensible language.

My research addresses the need for tools to make sustainable financial action more convenient, focusing in particular on college students. I leverage *design research* to find design concepts for *simple AI-based generative user interfaces* to help young adults participate in *sustainable financial activism*. Throughout my research, I conducted a survey of over 900 students from 20 universities across Taiwan and face-to-face user testing with 30 participants, enhanced by 6 expert interviews providing industry insights. The major contribution of the study is an interactive AI-assistant prototype.

Keywords: Human-AI Interaction, Digital Sustainability, Transparency