# Appendices

## Appendix 1: College Students' In-Person Prototype Testing Transcripts

Due to the large amount data captured by the in-person interview performed for testing with 32 people at 6 universities, I've chosen to exclude the full dataset from the PDF version of my thesis. The data is available upon request - and has also been published on Hugging Face as publicly: https://huggingface.co/datasets/krishaamer/taiwanese-college-students

Below is a small example of the data gathered.

{{< include "_sample-data-student-testing.qmd" >}}

## Appendix 2: College Students' Prototype Self-Testing Survey Data

Due to the large amount data captured by the survey (over 100 people self-tested the Green Filter app and 32 people filled out the survey after in-person testing was completed), I've chosen to exclude it from the PDF version of my thesis. The data is available upon request - and has also been published on Hugging Face as a public dataset here: https://huggingface.co/datasets/krishaamer/taiwanese-college-students

## Appendix 3: Expert Interviews' Transcripts

Due to the length, I've decided to exclude full raw interview transcripts. The data is available upon request. Below is one example interview transcript.

{{< include "_sample-data-expert-interviews.qmd" >}}

## Appendix 4: College Students' Survey Data

Due to the large amounts of data captured by the initial survey (over 1600 people started the survey, after filtering, leading to over 800 Gen-Z current college students finished it fully), I've chosen to exclude it from the PDF version of my thesis. The data is available upon request - and has also been published on Hugging Face as a public dataset here: https://huggingface.co/datasets/krishaamer/taiwanese-college-students

## Appendix 5: Research Tech Stack

For anyone who would like to repeat this research, here's a table with the software that this research project made use of.

| Tool/Service | Category                 |
|--------------|--------------------------|
| Matplotlib   | Data Visualization       |
| NumPy        | Scientific Computing     |
| jupyter      | Development Environment  |
| seaborn      | Data Visualization       |
| Python       | Programming Language     |
| VSCode       | Code Editor              |
| GitHub       | Version Control          |
| fireflies.ai | AI Meeting Assistant     |
| Google Meet  | Communication            |
| databricks   | Data Platform            |
| HuggingFace  | Machine Learning         |
| TypeScript   | Programming Language     |
| Tally        | Form Builder             |
| Zotero       | Reference Manager        |
| Quarto       | Publishing/Documentation |

| Tool/Service     | Category                |
|------------------|-------------------------|
| Apache Parquet   | Data Storage Format     |
| Haystack         | Search Framework        |
| MongoDB          | NoSQL Database          |
| langchain        | AI/ML Development       |
| GitHub Copilot   | AI Coding Assistant     |
| Figma            | Design Tool             |
| Sketch           | Design Tool             |
| OpenAI ChatGPT   | AI Assistant            |
| Anthropic Claude | AI Assistant            |
| Google Gemini    | AI Assistant            |
| Google Colab     | Development Environment |
| Google Sheets    | Spreadsheet             |
| META Llama       | AI Model                |
| Mistral          | AI Model                |
| OpenAI API       | API Service             |
| Postman          | API Testing Tool        |

| Tool/Service     | Category                     |
|------------------|------------------------------|
| Next.js          | Web Framework                |
| fullstory        | Analytics                    |
| Polygon.io       | Financial Data API           |
| Hotjar           | Behavior Analytics           |
| Lottie           | Animation Library            |
| Docusaurus       | Documentation                |
| Google Analytics | Web Analytics                |
| Google Maps      | Maps/Location Service        |
| vis.gl           | Data Visualization Framework |
| Pinecone         | Vector Database              |
| Vercel           | Deployment Platform          |
| Vercel AI SDK    | AI SDK                       |
| Radix UI         | UI Library                   |
| highcharts       | Data Visualization           |
| React            | Web Framework                |
| Tailwind         | CSS Framework                |
| Markdown         | Markup Language              |


## Appendix 6: Further Reading

Some recommended books on the topics covered in this thesis include, but are not limited to: 

- R. Buckminster Fuller "Operating Manual for Spaceship Earth"
- Victor Papanek "Design for the Real World"
- Jonathan Chapman "Emotionally Durable Design"
- Carlo Vezzoli "Product-Service System Design for Sustainability"
- Ezio Manzini "Design, When Everybody Designs".
