# List of Symbols and Abbreviations

Some of the key terminology used in my thesis presented in a concise format.

1.  AI - Artificial intelligence, a field of computer science and an umbrella term focused on a wide range of approaches to automation

2.  UX - User experience, a field of study and operational approach focused on how humans experience using systems

3.  AX - Algorithmic experience, a proposed category of user experience, that is focused on interfaces between AI algorithms and humans

4.  UI - User interface, such as in a mobile app, however increasingly audio, video, etc

5.  XAI - AI user experience, interaction design applied to AI concerned with how does a person or a group of people interact with the AI

6.  Fintech - Financial technology, the application of technology (usually AI), to classic financial services, such as payments

7.  ESG - Environmental, Social, and Corporate Governance, a new set of metrics proposed by the European Union, and adopted worldwide, to assess business and financial assets

8.  AI Assistant - software system providing the user with personalized suggestions based on machine learning algorithms

9.  Financial Advisor - a human financial specialist providing customized financial advice, including investment advice and services to a client

10. ML - Machine learning, a tool within the larger AI umbrella to enable computers to learn from large sets of data, which may be labeled (by humans) or un-labeled (auto-labeled)

11. HCI - Human-computer interaction, a field of study to improve human experience with information technology

12. OEM - Original equipment manufacturer, a company making products for another company that markets and sells such products under their own brand

13. API - Application Programming Interface, a method for software agents to exchange information in various forms of data: the basis for contemporary online services

14. EPR - Extended Producer Responsibility

15. SDGs - Sustainable Development Goals, a set of targets agreed upon by the nations of the world

16. LLM - Large Language Models

17. Vector Databases - specialized data storage for mathematical language embeddings in multi-dimensional space helpful for clustering similar concepts

18. CO~2~eq - CO~2~ equivalent greenhouse gases

19. GHG - Greenhause gases

20. PD - Participatory Design

21. VCM - Voluntary Carbon Markets

22. Hedge Fund - pooled investment fund

23. DAO - Decentralized Autonomous Organization

24. Zero Waste - according to Zero Waste International Alliance: "conservation of all resources by means of responsible production, consumption, reuse and recovery of products, packaging and materials without burning, and with no discharges to land, water or air that threaten the environment or human health" [@kalleZeroWasteTraining2022]

25. ESPR - Ecodesign for Sustainable Products Regulation

26. NFRD - Non-Financial Reporting Directive

27. CSRD - Corporate Sustainability Reporting Directive

28. EUDR - European Union Deforestation Regulation

29. Product Stewardship

30. Extended Producer Responsibility