# _quarto.yml
filters:
  - _table-short-captions.lua

format:
  pdf:
    filters:
      - _table-short-captions.lua
    variables:
      longtable: true
    include-in-header:
      - _headers.tex
    lot: true
    keep-tex: true