### Example Expert Interview 2024-05-19 - Chen-Ying Huang

MA Thesis: "Green Filter" (綠濾)  (2024-05-19 11:07 GMT+8) - Transcript
Attendees
Chen-Ying Huang, Fireflies.ai Notetaker Kris, Kris Haamer, Kris Haamer's Presentation
Transcript
This editable transcript was computer generated and might contain errors. People can also change the text after it was created.
Kris Haamer: Yeah, so let me repeat the question so I can get your answer into this recording.
Chen-Ying Huang: Okay.
Kris Haamer: So we're discussing the flow of the user and how it affects the decisions,…
Chen-Ying Huang: right So basically I'm thinking that people are lazy.
Kris Haamer: right?
Chen-Ying Huang: I look at myself. I'm really lazy When shopping and so you should if it's easier to get the information that I don't have to click on the button to receive the information. It's more likely that I will even pay attention to that and…
Kris Haamer: Right, right.
Chen-Ying Huang: also that words are very difficult to read through so I don't really have incentive to read a lot but it was just a picture and showing that the product somehow it's green like saving whatever picture you can put on the iceberg or the polar bear or whatever that's
Chen-Ying Huang: That will immediately let me realize that this product is green and maybe there it could be a scale like House Green it is from zero to a hundred and then I can immediately know how green this product is.
Kris Haamer: even
Chen-Ying Huang: Maybe there would be infected on me. So I'm thinking more along this line.
Kris Haamer: right, right, visually understandable or really quickly understandable images instead of this kind of report.
Chen-Ying Huang: right Yeah.
Kris Haamer: Yeah. I haven't tested that how this research started was from my kind of own interest that I don't even ever rushed Star Trek, the science fiction so it has some medical professionals and they'll have a scanner and then they can scan your whole body,
Chen-Ying Huang: Yeah, yeah. Okay.
Kris Haamer: just by waving the scanner and they will understand what's wrong with you. So every time I bought some product I felt like I want this kind of scanner just to give me a quick information about is this a good product? And I thought I try to build something like that.
Chen-Ying Huang: Okay.
Kris Haamer: But then I realized if I actually want to make a working prototype and this is really difficult to do on a mobile phone, even though that would be the obvious choice. Because the Apple ecosystem is close so you can't really do a lot of things. On the mobile phone, but on the Google Chrome browser. It's very open so I can take any website like Momo and I can just kind of rewrite the page. Using the plugin.
Chen-Ying Huang: Okay.
Kris Haamer: So that's how I ended up, going to the online shopping and more particularly. And then, actually make it technically work. Then AI is slow that is the main question. So if I kind of breathe premade these pages and then test it I could do, those kind of pre-made images or pre-made reports. But this is actually working in real time. So you can go to any page on Mama and it will do this analysis. using actual data so that is the reason why there's a button instead of kind of a primate bring my thing and then Maybe I'll just kind of continue from So down here. I also came up with this kind of scoring.
Kris Haamer: Because my intuition was that maybe the social. aspects of a product so other people who bought the product
Kris Haamer: and their opinion of it could also be relevant but so far among those, 20 people actually, saw this they didn't honestly understand what these numbers were or why they were there none of them understood it. and then if you can actually get down here, there's another button that takes you a new page and
Kris Haamer: then you get to the actual app kind of part which is much bigger and that I have more control over than a Momo page because even though the Chrome browser is quite open still there are a lot of limitations on for example, how can I attract the user? So if you come to this page I can track where do you scroll and where does your cursor go and a lot of detail about your usage of this page. I can track all of that and use that data.
00:05:00
Chen-Ying Huang: Wait, so you are not right randomly sampling people from Momo, right? You are asking subject to participate in your experiment, So in that sense,…
Kris Haamer: Yes, yes.
Chen-Ying Huang: wouldn't it be possible that? So you want a natural environment where there are shopping? Is that the idea? Otherwise, why wouldn't it be possible but then to read some information about the product here the information you provide before they really look at the specification of the product itself.
Kris Haamer: Mm- So yes, I think because I'm from the design department. So our approach to doing this experiments is not very scientific. So a lot of times I don't know we've heard about design thinking is kind of a type of I would say quasi research. you do some workshops or you get some people and try to
Kris Haamer: Use this kind of format of it's called The Double Diamond. So you kind of try to get some kind of data from out of it, but it's not scientific at all. It's just mostly try to give you some kind of keywords or intonation what would work so I try to do better than that and do this kind of survey which as my Chinese and isn't enough to do this kind of interviews with people really or things like that. So I focus on a survey And the survey mostly. it's 63 questions so I can get a lot of data from that and then I use some kind of Gaming's K means so it's a computer algorithm that takes all of this data.
Kris Haamer: Points and then create free profiles based on similarity. So maybe I just shared that patient.
Chen-Ying Huang: Mmm Yeah
Kris Haamer: It's easier to talk about if you can actually see what I did.
Chen-Ying Huang: It from the survey data.
Kris Haamer: Let's hear that.
Kris Haamer: so this is the three type of personas they came up with from the data and…
Chen-Ying Huang: Okay, okay.
Kris Haamer: Yes, yes, and there are different ways to do that. This is based on
Chen-Ying Huang: so basically that one Persona is that they really care about the environment
Kris Haamer: all of the data you could I also had a part that I only had questions about kind of product features what you want and then I could get different types of personas based only on that single question. and a little bit different but yeah, so basically I got this three personas and
Chen-Ying Huang: yeah.
Kris Haamer: Yes, so this is the most friendly one. But if you look at the three different personas, there's this overlap concern on things. So like I mentioned before the product origin, it's relevant for edit pretty much, most of the people who did the serving. and then The materials is more important for the parently Persona and…
Chen-Ying Huang: Okay.
Kris Haamer: less for Frugal they will care more about money if it's expensive or not. And they're like the social aspect, I had the social score interact actually, most of the people maybe didn't understand or didn't care about it. So at least It wasn't relevant. so basically After doing all of that. I still need to. Test what I actually built. and I was talking to my professor from about different ways of doing it And the citation was just go one more one by one and get people to use the actual app. not give that much information and then kind of see what they do with the app and how far they get.
00:10:00
Kris Haamer: because if I go back to what was the actual idea of the research was that? I thought maybe.
Chen-Ying Huang: but
Kris Haamer: Maybe it can be a journey, maybe the product is an entry point. And I could create a funnel and get those people. To invest into that company in some way. So investing here means in a really white sense, either just buying those products from them or efriendly company, or maybe becoming like a shareholder.
Chen-Ying Huang: no.
Kris Haamer: And when I started this I I can do this. But by now I'm thinking this is way too big of a project for a master's degree. Because shopping and there's even saving here and investing. There's so much different research about each of them and there's not much overlap. and maybe I'm kind of in a somewhat, new territory trying to combine those things and why I maybe had the courage to try to combine those things is because I was just right naive and not with an economics background or…
Chen-Ying Huang: don't
Kris Haamer: not without Finance background. I was thinking in terms of the user interface. And I can build this funnel and get those people into that funnel and…
Chen-Ying Huang: Okay, okay, but it's still good to have a dream.
Kris Haamer: maybe get them to the end. But now when I'm realizing that I can't even get people from the moment page into my app…
Chen-Ying Huang: 
Kris Haamer: because most of them disappear, in the first step. Then I start to realize that the investing staff is so far that maybe Sears here or zero point one person that people actually get there.
Chen-Ying Huang: Know yeah. Yeah.
Kris Haamer: but yeah.
Kris Haamer: But I mean maybe it's also valid for research to say it is, it's really hard to get those people from point zero to that far away place and that's a really outcome.
Kris Haamer: Yeah, but coming back to this app. So, as I think there's shopping there's savings and there's investing. And actually trying to build that funnel. how do you build that funnel? So I ended up. because chat CPT so popular are so in many ways. I try to build friendly Church APD here.
Chen-Ying Huang: Okay.
Kris Haamer: and give the user Some questions and…
Chen-Ying Huang: I'm fine question really interesting. Where can I buy those products in Thai not I think that's a useful question.
Kris Haamer: those questions are mostly based on the service.
Chen-Ying Huang: That will attract my attention.
Kris Haamer: What was seem to be relevant in the survey? And you can ask your own questions.
Kris Haamer: But most people when the tested it they didn't really know…
Chen-Ying Huang: Yeah, yeah.
Kris Haamer: what to ask.
Kris Haamer: Yes, I try to be localized. it seems that the more precise and relevant and personalized you are more the higher the conversion rate, it seems that you're talking about a specific thing.
Chen-Ying Huang: Okay.
Kris Haamer: and then this is not ready yet, but Let's say I will ask it.
Kris Haamer: right
Kris Haamer: just use this keyword. And it will generate.
Kris Haamer: so this page is not ready, but it will generate for example a map of factories. And so you could see how this product actually comes from here. And then maybe you could see pictures from the factory. and why I started build this page is Particularly for food products. So let's say from buying milk or meat or whatever, a food product you could ask about the product and you can see how far it came from, but the conditions of those animals there.
Kris Haamer: And maybe those pictures could be like a live stream or…
Chen-Ying Huang: it's
Kris Haamer: you could have a really transparent insight into what is food and where it came from. But that data is very hard to get. I guess so. So for now, it's just like a mocha. That's right. It is not real data.
00:15:00
Kris Haamer: because this is I said a journey, So I kind of had this section of here so you could set your kind of Financial goal. What do you want to achieve?
Kris Haamer: Based on the testing it seems that the students who got to this page. Mostly they had really similar ideas about the future, because they are better students. So they talk about how maybe I wanted to master degree or get a job or those people nobody said they'd want to start a company or anything Really entrepreneurial most of them gave a really standard answer. So actually it ended up not being so useful.
Chen-Ying Huang: Okay.
Kris Haamer: I thought first Maybe I could, have a really specific code here. Because the AI will take that into account. I could give them more specific advice. And then, we talked about investing so I had this idea of having your kind of stock portfolio here. So this is actually real data. and when I started to get this data, I also want to
Chen-Ying Huang: Okay.
Kris Haamer: have ESG data live here, but then I realized and that was actually crucial finding for me. Yesterday that I so expensive. To get this graph up here it cost maybe for the USD. This is stock data from us markets. But if I want to get ESC data here, it costs 4000 USD.
Kris Haamer: 4,000 and as a consumer that's already obviously, impossible, there should be someone paying that cost. but currently ESG data, even though it's exist and it's monthly so far. It's not real time, but it's monthly monthly is pretty good. So you have monthly data about the company and to see how they're doing in terms of, their approach to environment and social and governance. And you could have that on the product page even on the mobile page. Maybe that would have some kind of influence because you could see how this seems really transparent. And this company recently, is not doing so well in terms of paying their employees or the approach to nature. Maybe I will avoid this product.
Kris Haamer: But currently I couldn't get that data. I only got data for companies that actually take their own data and put them on their website for free. I could get that data. So right now the only way I could do that is to make a fake mock-up maybe only users couple of companies that I could get every data for but the real data that wasn't monthly that was from the last year. So there's this time difference. So as you can see, it's goes into many different directions because where I work on this I can see they're like
Kris Haamer: Rabbit holes to go down into right and in my email, I even mentioned, particular talk about economics in Europe. We have more and more people talking about the growth and donut economy and all this kind of A new economics I guess. more people are talking about that. and that's one of the reasons why I want to have this call to have an actual Economist talk to me about this topics. because if I read those papers and if I look at what those people are talking about and mostly they're saying which is
Kris Haamer: Me to produce less and produce better things. and…
Chen-Ying Huang: just
Kris Haamer: just kind of reduce the economy and not have economic growth at least in particular sections of the economy and maybe have economic growth in some section of the economy. I know these are kind of no-go areas,…
Chen-Ying Huang: Actually, I haven't read anything about that are interested in that I can properly introduce a colleague of mine to you that he might be more likely to have read that.
Kris Haamer: I guess from Media because economic growth is what politicians talk about at least in Estonia. I guess also in Taiwan and…
Chen-Ying Huang: So just from reading your email,…
Kris Haamer: and when I get your sense of these new economic.
Chen-Ying Huang: I thought that I can contribute a little bit probably just a little bit that into your first goal trying to influence the shopping Behavior.
00:20:00
Kris Haamer: I guess new models. And have you read anything about it, or have you had any interest?
Chen-Ying Huang: So the other goals I think are a bit big for me. So
Kris Haamer: Okay.
Chen-Ying Huang: my intuition is just to make the information relevant and simple. So then you have better chances to influence the shopping behavior and most in I talk about introducing an option that is obviously worse and sometimes it works. So if you have instead of one option at the one time then you have A decoy option that is obviously in terms of environmental friendliness that it's even worse than the target. And then in my make it.
Chen-Ying Huang: Yeah.
Chen-Ying Huang: Yeah.
Kris Haamer: So if you go to this moment page, so one thing that I would say. a lot of people mention was curious for me was the sidebar and left side. So they would look at the alternatives. and so In terms of the environmental report, I don't even focus on this particular product. So if you have some kind of decoy…
Chen-Ying Huang: right Right,…
Chen-Ying Huang: nothing one most useful way. Is that the maybe…
Kris Haamer: then that would be like a product comparison maybe and…
Kris Haamer: to have those reports made for a bunch of products and…
Chen-Ying Huang: if I revealing that how much the company would actually invest or…
Kris Haamer: in that category and…
Chen-Ying Huang: spend the
Kris Haamer: have some kind of like a sidebar or…
Chen-Ying Huang: Spent their profit in green organization,…
Kris Haamer: Capital products similar products similar category may be…
Chen-Ying Huang: that would be Costless to the consumer,…
Kris Haamer: but different scoring. on this report Okay.
Chen-Ying Huang: but that kind of information. May help in the sense that I feel that I'm paying the same amount of money to firm Ai but would be contributing part of the profit to the society then it's like a free good to me. So I Would be more willing to do that conditional on that. They are competitive in terms of price.
Chen-Ying Huang: Works. Yeah. Yeah, so that would probably work. but Detail information like this. I think you are targeting experts instead of a general consumers that…
Kris Haamer: right
Chen-Ying Huang: who are just rushing and buying things out of I don't know I think that to them or…
Kris Haamer: Right, right. It would make it very obvious,…
Chen-Ying Huang: to me. I think the key Point still whether the product has the specification that I want and…
Kris Haamer: which is the better choice.
Chen-Ying Huang: whether the prices reasonable and…
Kris Haamer: Okay.
Chen-Ying Huang: whether it is it has a good reputation that it's durable than the product is good. So How to kill that it's not very easy, but there's still some ways I can do it. What have you tried to search? some web pages where they try to sell green products, they must have figured out a way.
Kris Haamer: Right, right, right.
Chen-Ying Huang: yeah.
Chen-Ying Huang: Okay, okay.
Kris Haamer: Yes, yes, so mostly there's just Queen shopping malls that green Online stores and they will create those products for you. but Kind of my understanding is you have to be already a green consumer before? So to go to those pages because they are not those amazing pages. So that's why I focused on Momo and this app also works on Shall be another coupon and other kind of very mainstream I guess coupon is the new one growing one. But then the issue that came up was, even more basic and the more I research it seems like just the very basic issues are where people get stuck, right? so
Kris Haamer: On coupon and on shopee just a layout of the page is different. And so it's really hard to see this AI box into that layout.
00:25:00
Chen-Ying Huang: But I mean for those spring web page,…
Kris Haamer: And…
Chen-Ying Huang: they still have to sort of.
Kris Haamer: we couldn't really find it and…
Chen-Ying Huang: Do they still reveal some information about…
Kris Haamer: and more modern there's just kind of more space for it layout at the moment makes it easier to put the AI here that's the reason…
Chen-Ying Huang: which product it's Greener? I mean all of the products are green. No, so they don't.
Kris Haamer: why I focused on Mama because it seems that even though half of the people gonna find it on Momo, but on the other Pages it was even harder.
Chen-Ying Huang: Okay.
Chen-Ying Huang: Yeah.
Kris Haamer: No. No, no. No, they don't really to Discount comparisons. They just create a bunch of products and they say this is called King Green products. So they go into much detail, but there's a bunch of kind of rating sites, especially for particular Industries. For example, in There's the fashion transparency index. And they will do product analysis and brand analysis and they will go into a lot of detail. So, if I want to focus This research on your fashion that would and…
Chen-Ying Huang: he
Kris Haamer: closing that would Help me to actually make those kind of reports much more precise.
Chen-Ying Huang: Okay.
Kris Haamer: but then the problem becomes like when I want to test Momo and then should I ask the user look for a brand of clothes that you like or for now, I just keep it very open. I just ask them to look for any product that they like because I thought that would be more relevant, if they have brand family.
Kris Haamer: But then it becomes that. They look for the product that they like and…
Chen-Ying Huang: You are asking people to look for the item they want but at the end that there's still looking for the aspiration item,…
Kris Haamer: mostly it's a brand that is an aspirational brand, people look for luxury brands or…
Chen-Ying Huang: I mean it's even…
Kris Haamer: you…
Chen-Ying Huang: if they look at the camera still it's not a purchasing experiment in your survey,…
Kris Haamer: they can't afford. And how useful is that really because if you look for things that you can afford you're not gonna buy anyway.
Chen-Ying Huang: It's still possible that just look up at the camera.
Kris Haamer: So, why look at the sustainability report?
Chen-Ying Huang: But at the end I still don't buy it. So in that sense. that
Chen-Ying Huang: Okay.
Kris Haamer: Yes, so I think the way I tested this currently not working. So I kind of want to redesign my testing and try to do that before this semester ends in June.
Kris Haamer: And I'm a little bit confused. what would be the best way to do it? And so I thought because now I managed to make this available on that Google web app store so you can actually download it yourself to your browser.
Kris Haamer: So because the survey works so well and the survey works so well because it's mostly people just filling it out. I thought I'd try to. get more data like this to have to ask people to download it and then fill out the survey And so the survey is actually the same survey and then I could do matching. What type of persona they…
Chen-Ying Huang: So basically your idea now is that you the subject or…
Kris Haamer: because currently what happens. Is that even though do the testing I don't know who they are.
Chen-Ying Huang: whatever that in your experiment would do the survey first.
Kris Haamer: So it becomes kind of disconnected from my survey results,…
Chen-Ying Huang: And then they will have this purchasing.
Kris Haamer: but if they fill out the survey then Even if I have a little bit of data about the usage. It's useful because I know who they are.
Kris Haamer: Yeah.
Chen-Ying Huang: mmm
Kris Haamer: And I would ask them to kind of download to their own computer because I'm also realized if they do all my computer. So the way I did it, I just went to people on campus and asked them and then I helped them to kind of use it on my computer. but instead of doing that I could reduce my own implants on it and asked them to download their Chrome browser and Chrome is likely used, it's like three billion people. Everybody has a growing browser. So if they downloaded their own browser,
00:30:00
Chen-Ying Huang: Then I think you probably only need to have two apps one is green app.
Kris Haamer: they will feel more comfortable maybe in that environment on their own computer instead of having to you…
Chen-Ying Huang: The other is not so green at or…
Kris Haamer: And kind of telling me…
Chen-Ying Huang: it's just a control app. And then whatever experiment you want to run.
Kris Haamer: what they want to do and especially because we're doing it in Chinese,…
Kris Haamer: So there's a lot of data loss, if they say something that I don't understand in Chinese and…
Chen-Ying Huang: And the remaining whatever experimental surveying one…
Chen-Ying Huang: who runs stay the same. So you ask a set of people try to install the app?
Kris Haamer: already that information is gone.
Chen-Ying Huang: One is the green app. The other is a control app. And then you try to compare the difference of behavior. Maybe the hypothetical purchasing Behavior at the end. It has an effect then it has an effect. because the two groups are randomly assigned to the app so you can reasonably assume that it's the app that is making the difference.
Chen-Ying Huang: So this way you don't. Yeah, you just have to figure out a controller. to do that
Chen-Ying Huang: you can do it step by step.
Kris Haamer: Okay, right.
Kris Haamer: right I kind of Realized that and…
Chen-Ying Huang: Yeah. Yeah.
Kris Haamer: makes me very sad because I wanted to get people down the funnel through the actual.
Chen-Ying Huang: Okay.
Kris Haamer: Yeah, yeah. Because I'm losing a lot most of the people on the first or second step. So all of the work I put into building all that AI stuff. most of the people don't even get there so Yeah,…
Chen-Ying Huang: so, can you show me the first click a little bit Can we go back to yeah.
Kris Haamer: so I somehow.
Kris Haamer: I also don't feel like you have to separately because how did they get there? there's no context for them to get there. But if it's inside a mama and they will click on the button. Then it creates the context that they would,…
Chen-Ying Huang: Recently, I'm thinking about travel. so
Kris Haamer: be kind of on that first step of the funnel.
Chen-Ying Huang: it's a travel like Maybe plane ticket whatever.
Kris Haamer: Right let's Tell me that you tell me a product that you like or…
Chen-Ying Huang: But it's not a moment. So Let's say luggage.
Kris Haamer: a brand that you like.
Chen-Ying Huang: Okay, whatever.
Kris Haamer: anything that's like okay, let's say
Kris Haamer: Right. I don't think. exactly, so
Chen-Ying Huang: So where's your click,
Kris Haamer: My very slow here. Which one would you pick here?
Chen-Ying Huang: Okay.
Kris Haamer: that's
Kris Haamer: Mm-hmm, Because the Internet is slow in Macau.
Chen-Ying Huang: is this only place you can put it?
Kris Haamer: I think it's takes a while to load. But yeah now it's here.
Kris Haamer: So currently looks like that and…
Chen-Ying Huang: Okay.
Kris Haamer: then you actually have to click on here but because
Chen-Ying Huang: Okay.
Kris Haamer: A lot of people missed it. So I'm thinking I was just making more obvious
Chen-Ying Huang: That's okay. That's okay. That's okay. Just thinking you put it next to the price. Okay.
Kris Haamer: so putting some kind of like
Kris Haamer: I plan to put it next to the price because Okay,…
Chen-Ying Huang: Yeah, sure.
Kris Haamer: right now there's Danica problems.
Chen-Ying Huang: So what is the percentage of people clicking?
Kris Haamer: I think it's because I'm in my car.
Kris Haamer: I am
Kris Haamer: Yes, yes. Because I would say most of the people will look at the price,…
Chen-Ying Huang: about half okay.
Kris Haamer: So that next to the price then you would say it.
Chen-Ying Huang: a half
Kris Haamer: so out of those 20 people who would click it without me suggesting it would be about half. But yeah, but because I want to get them to the next page then I suggested it and then I got those other half the coaching the next page. Yeah.
00:35:00
Kris Haamer: and then we can also just
Kris Haamer: just ask for a travel product here
Kris Haamer: What's the brand Travel Fox? Okay.
Chen-Ying Huang: Okay, yeah.
Chen-Ying Huang: It's an interesting thought and it's really impressive that you put this into action and…
Kris Haamer: I think there's some. Problem with the internet here…
Chen-Ying Huang: already come up with this so far.
Kris Haamer: because it's just not loading.
Chen-Ying Huang: Yeah, but I feel that…
Kris Haamer: Yeah. yeah,…
Chen-Ying Huang: if you can. Somehow increase the …
Kris Haamer: I realized the internet is much more restricted and
Chen-Ying Huang: I think my only question would be that how do you make it more? Likely that people click on the first button and then after you they click on the first part and how do you make sure they click through it and look at more information? I think that's a key to me.
Kris Haamer: right
Kris Haamer: I think that's useful for me also…
Chen-Ying Huang: bye.
Kris Haamer: because it's kind of confirmed concern That you as an economic Economist think about this funnels in a very similar way, as like website marketers or startup people. They think about how do they grow their company and most it's about, getting people that the next page,…
Chen-Ying Huang: I have a colleague…
Kris Haamer: you…
Chen-Ying Huang: who yeah,…
Kris Haamer: keep getting people to click through the payment and…
Chen-Ying Huang: he's an econometrician,…
Kris Haamer: actually doing the payment and…
Chen-Ying Huang: but he's doing climate change.
Kris Haamer: there's people disappearing on age that
Chen-Ying Huang: So I can't email him and…
Kris Haamer: And …
Chen-Ying Huang: and put you into contact with him.
Kris Haamer: you said that you had a colleague…
Chen-Ying Huang: And also I also have a colleague…
Kris Haamer: who would maybe relevant, you…
Chen-Ying Huang: I believe she is in the international business department of NTU go Mount Si.
Kris Haamer: who are the Red, more about the new economics?
Chen-Ying Huang: And she's basically doing marketing. So if you want to have I believe that she has done some more feel like experiment like this.
Kris Haamer: Okay.
Kris Haamer: that would be amazing. Yeah.
Chen-Ying Huang: so if you need help in
Chen-Ying Huang: How to make people clicking through your web page. I think she is a better person than me to approach you. because she knows a lot more marketing people knows a lot more.
Kris Haamer: Okay.
Chen-Ying Huang: Though It's just like a Layman idea, but she will know better. So I think I can write an email and put you into contact with these two colleagues then. Yeah, yeah.
Kris Haamer: Okay.
Chen-Ying Huang: is
Chen-Ying Huang: yeah.
Kris Haamer: Thanks so much. That would be amazing. Yes. I'm also trying to wrap all of this into a presentation that fits into this is defense. And it's just way too many things. But I still need to.
Kris Haamer: have some type of rounding to it and the grounding would be I guess just like the economic theory and the idea that many people are trying different things to fight climate change, right and I'm gonna mention that there are those people, think of macroeconomics and…
Chen-Ying Huang: But that sounds more like a motivation of your research,…
Kris Haamer: think about, just producing the economy and…
Chen-Ying Huang: So I wouldn't worry that much about that.
Kris Haamer: and not having growth and…
Chen-Ying Huang: I will worry more about the click through rate…
Kris Haamer: I kind of Need to put all of those Concepts into concept map for my teachers to understand…
Chen-Ying Huang: because that's where the data is from. So I think that by talking to other people that will help you design or…
Kris Haamer: where worries my research base right why I'm focusing on this stuff here.
Chen-Ying Huang: change a little bit.
Kris Haamer: Because there are so many different ways to approach climate change.
Chen-Ying Huang: And then you can have a higher click through that rate.
Kris Haamer: and so
Chen-Ying Huang: Then you will be able to do whatever you want to do, right? So.
Kris Haamer: yes, yes. Yes.
Chen-Ying Huang: I think that's a key. Yeah.
00:40:00
Kris Haamer: Okay, okay.
Chen-Ying Huang: right if you change it to other things then and then you see the difference now.
Kris Haamer: Right, right.
Chen-Ying Huang: so much without the teacher just This is more a questioning mark instead that you try to say something nice or…
Kris Haamer: yes, yes and in that sense, and if you look at
Kris Haamer: The moment page, just changing that, one sentence in Chinese here. could be like a key,…
Chen-Ying Huang: something in a positive way.
Kris Haamer: because some people say it's very awkward right now. but
Kris Haamer: Why it's so weighing in our sense is because I didn't want to specifically say this is like a sustainability report.
Chen-Ying Huang: You said you want to stay neutral, The emergency.
Chen-Ying Huang: How did you touch so much Champion?
Kris Haamer: because I was afraid of preaching to the crowd in a sense, I wanted to be Kind of General enough that even…
Chen-Ying Huang: Yeah. Yeah.
Kris Haamer: if you're not the green crowd, you are just don't really care about sustainability person. You will still click on it. And maybe you will learn something.
Chen-Ying Huang: There could be better ways to phrase achy PT can help you with that. Just skiing this straight.
Kris Haamer: Yeah.
Chen-Ying Huang: okay.
Kris Haamer: because people care about money right people care what happens to their money,…
Chen-Ying Huang: Okay.
Kris Haamer: so that's why That's yeah.
Chen-Ying Huang: Can you scroll down a little bit? let me just want to see the whole box. Okay, two sounds yeah, okay.
Kris Haamer: What I've had maybe 50 versions of that. But how long did I focus on that? Yeah, I manage my time well.
Chen-Ying Huang: Because it's a gp's randomness.
Kris Haamer: 
Chen-Ying Huang: Okay, and you talk to the marketing person that we're introduce you…
Kris Haamer: I think it's working again.
Chen-Ying Huang: but it's me that I probably will shorten this information. And so then there is a chance to read it. there are I believe.
Kris Haamer: And the report is going to be different every time. because
Chen-Ying Huang: Probably is hard the spot. No, it's almost unlikely to collect that information.
Kris Haamer: yes, yes.
Chen-Ying Huang: I'm thinking that there are some simple eye trackers using the camera that you
Kris Haamer: right and
Chen-Ying Huang: you can really identify what the person really reason.
Kris Haamer: Sorry, what do you mean?
Kris Haamer: Yes. Yes. we have a lab at ncu.
Chen-Ying Huang: yeah.
Kris Haamer: Who does that? but it's
Chen-Ying Huang: so No,…
Kris Haamer: I know people. Doing that they do it fulfillment analysis and…
Chen-Ying Huang: no, that's not the good idea. So maybe just don't overload yourself.
Kris Haamer: there are other people doing it also,…
Chen-Ying Huang: So maybe the one way to do is to simplify each window so every step this person really wants to go on…
Kris Haamer: but that equipment it's a little bit hard to book. Because a lot of people want to use it.
Chen-Ying Huang: then he had to click it and…
Kris Haamer: I feel like I'm already over my head with this project a little bit.
Chen-Ying Huang: then you just track how many clicks this person goes through and…
Kris Haamer: So I'm not sure adding another layer.
Chen-Ying Huang: this way it's just like an easy eye tracker instead of it's a mouse tracker.
Kris Haamer: Yeah. Yeah.
Chen-Ying Huang: So it's a quick tracker. You can do that.
Kris Haamer: Right, right. Yes. Yes, I can do that and I'm actually doing it right now, but I can only do that. Unfortunately on the page that I control Which is this one,…
Chen-Ying Huang: Yeah.
Kris Haamer: So once they get here? but if they get here each report has this ID here,…
Chen-Ying Huang: Dry, but you talk to the person but I think that was simplify this page.
Kris Haamer: so I'm tracking it through the ID so I know…
Chen-Ying Huang: Because I wouldn't read it.
Kris Haamer: which type of report they got and…
Chen-Ying Huang: It's to be honest. I wouldn't read it or…
Kris Haamer: I know which product they were looking at and…
Chen-Ying Huang: by word. Yeah, make it simpler then.
Kris Haamer: things like that, and I know that they click on this button here. But I didn't see anything else…
Chen-Ying Huang: Probably then you will have more influence on that.
Kris Haamer: because Google Chrome just doesn't allow it.
00:45:00
Chen-Ying Huang: Okay, okay.
Kris Haamer: Okay.
Kris Haamer: Okay.
Kris Haamer: right I think that's really a lot of help from you. So I thank you.
Chen-Ying Huang: I just try to email you and…
Kris Haamer: Thank you so much. And very nice talking to you.
Chen-Ying Huang: the two colleagues separately and then you can contact them. If you feel that. It's helpful and I think that you actually the talking to the economic attrition. It should be fun, but I don't think it's so necessary. It's just justification like some economists say that we should care less about growth.
Kris Haamer: You right in a sense. I want to just have expert kind of confirm what I have written in the thesis,…
Chen-Ying Huang: okay. Yeah.
Kris Haamer: which is, mostly from the literature and if I can have an actual person with an expert to say similar things that I read and…
Chen-Ying Huang: Yeah, he's very nice person.
Kris Haamer: That's useful.
Chen-Ying Huang: So I think he can help you on that. But I would really encourage you to talk to the board. She see the large should because she is an expert in marketing. I don't think she should be able to help you with the design. That's a meat so.
Kris Haamer: okay.
Chen-Ying Huang: Yeah, all Right. Thank you.
Kris Haamer: That would be great. Thanks so…
Chen-Ying Huang: It it's very impressive.
Kris Haamer: Yeah, okay. Thank you.
Chen-Ying Huang: Yeah, I will be very happy my student come up with an app like this.
Kris Haamer: Thank you.
Chen-Ying Huang: Yeah for What's your all right,…
Kris Haamer: Okay.
Chen-Ying Huang: okay, so I'll email later. Bye.
Kris Haamer: Thank you so much. Okay, yeah. Bye-bye.
Meeting ended after 00:48:18 👋