---
title: Conclusion
bibliography: [ref.bib]
csl: harvard.csl
sidebar_position: 8
editor:
    render-on-save: false
suppress-bibliography: true
---

# Conclusion

Draft: "The research paper explores the potential of leveraging artificial intelligence (AI) to guide young adults, specifically Taiwanese college students, in making more environmentally and financially sustainable choices. It delves into the interconnectedness of economic behavior, ecological sustainability, and human health, underscoring the critical role that financial decisions play in impacting the planet's health. The study presents an AI-assisted prototype designed to simplify and encourage sustainable financial practices among college students, addressing the need for accessible tools to foster environmental stewardship through financial activism."


"a comprehensive study on designing a financial AI companion to help college students make more sustainable shopping, saving, and investing decisions. The research combines insights from fields including sustainability, finance, AI, and design to propose an interactive AI-assistant prototype that can guide users towards environmentally-friendly choices."

"Survey results from 700 college students across Taiwan highlight concern among young adults regarding environmental degradation. However, it acknowledges the barriers these individuals face, including a lack of accessible tools and clear information, which hinders their ability to contribute effectively to environmental sustainability. The research underscores the importance of designing AI interfaces that are not only user-friendly but also capable of translating complex environmental data into actionable insights. The prototype resulting from from design research aims to empower young adults to make informed decisions that align with their environmental values, whether through sustainable shopping, saving, or investing. Testing with 30 students at NCKU provided additional changed in the app design."

"The study employed a mixed-methods approach, starting with a literature review to identify key concepts, followed by expert interviews to gain industry insights. A survey of 700 college students across 10 universities in Taiwan was then conducted to understand their preferences and attitudes. The major contribution is the interactive AI-assistant prototype, informed by the design research findings.

In conclusion, this research addresses the need for convenient tools to enable college students to take sustainable financial actions in their daily lives. By leveraging advancements in AI and data-driven interaction design, the proposed AI companion aims to act as a translation layer between complex environmental data and human-comprehensible language. The prototype demonstrates how thoughtful design can empower the next generation to align their consumption and investment behaviors with their concern for the environment, driving positive change through their financial choices."