---
title: Discussion
bibliography: [ref.bib]
csl: harvard.csl
sidebar_position: 6
editor:
    render-on-save: false
suppress-bibliography: true
---

```{=mdx}
import Embed from '/src/components/Embed'
```
# Discussion

I propose *interfaces* and *workflows* to see financial interactions through the filter of sustainability.

What kind of sustainability info do college students care about? How would college students prefer to interact with the AI? What role would college students prefer the AI to take? How can college students trust AI? What can college students do to aid sustainability efforts? How might AI assistants help college students find shopping, saving, and investing opportunities?

"Systemic change through financial actions driving policy and market changes encourage broader industry shifts towards greener practices".

Overconsumption-driven extractive business practices contribute to the degradation of Earth's natural ecosystems, pollution of water, air, and soil, deforestation, diminishing biodiversity, climate instability, extreme weather, modern slavery, worsening human health, and other environmental and social challenges (ADD CITATION). Companies are attuned to consumer demand however widespread greenwashing makes it tiring to find sustainability-focused companies and requires extensive time for research. Even for highly motivated people, it’s difficult to know what’s sustainable.

My interest lies in understanding how AI assistants can help conscious consumers become sustainable investors. The purpose of this study is to explore how to provide the best user experience to potential sustainable financial AI companion users. In their sustainability report every company looks perfect. How can people shop, save and invest sustainably? Where does our money go and what are some greener alternatives? The companion enables people to be more transparent and responsible in their consumption behavior.

in taiwan water is too pollutee can't swim

air is too dirty can't breather (show my own stats)

start local then go global with backup data from global sources

ask chatgpt how to organize my sections

rq: how to connect env destruction pollution to source causes

rq: how to connect everyday financial actions to environmental impact in a visual/ meaningful way

idea came riding my bike in annan can't swim in yhe annan river

show local pollution map?

show factories on the map

instead of the browser pluging just make a website where you can share the link of the product (and cache rhe results)

on ios can use the share screen to share to the app?

ICID calls upon us to have the courage to redesign entire industries

This research takes place at the intersection of Taiwanese college students, sustainability, finance, AI, and design.

For the average person like myself, my experience with money is mostly limited to buying things at the supermarket. Food, clothes, furniture, soap, mobile phone. This leaves very few options on how to start with something new like saving and investing.

Could the Green Supermarket become the entry point to Green Savings and Green Investing?

Oboarding more people for sustainable practices is a complex interaction design issue hindered by ambiguous data (what is sustainable?) and messy human motivations (we love buying things).

What can people who want to preserve Earth's environment, exactly do? How can networks of people come together?

Health tracking apps paired with connected devices such as Apple Watch filled with sensors provide one model for simple interactions to dynamically track digital health data - also known as a quantified self. This data allows apps to provide tips how to improve health outcomes through small daily actions such as climbing more stairs. Small interactions allow users to align their goals with their actions.

What would be a good interface to track sustainability? What is the user interface at scale, useful for billions of people?

One way to influence societal outcomes is to decide where to put our money. While our financial decisions are a vote towards the type of businesses we want to support, is it enough?

While some people are demanding sustainability, and some governments and companies are announcing green investment opportunities, how can consumers discover the most suitable investment options for their situation?

How can retail investors access and differentiate between eco-friendly sustainability-focused investable assets?

The level of knowledge of and exposure to investing varies widely between countries and people.

Could linking green consumption patterns with sustainable investing provide another pathway to speed up achieving climate justice as well as personal financial goals?

In this simplified scenario, I'm in a physical offline store, doing some shopping. When putting a bottle of Coca Cola in my basket, my AI companion Susan will ask me a personalized question:

Does individual climate action help?

Gen-Z college students (target users) may not have the capital to make a financial dent today however they can be early adopter and they will be the decision-makers in a few years.

"Like climate change, the focus on individual actions as a solution is often misplaced, though it remains a focus of media and industry. For decades, the petrochemical industry has offloaded responsibility onto individuals through promoting concepts such as the"carbon footprint", championed in a 2004 advertising campaign by British Petroleum" [@cherryProfitRethinkingCorporate2010 in @laversFarDistractionPlastic2022].

Individual efforts are too small to matter unless they're inspired by Community a effort

atmospheric pollution and climate change

The latest IPCC report @calvinIPCC2023Climate2023

@dimockDefiningGenerationsWhere2019

kora 95% https://kora.app/

I, as the researcher, am similar to the blind people in the elephant story; focusing on greening shopping, saving, and investing are only the trunk of the enormous elephant that is environmental disaster unfolding in front of our eyes.

## Results

The research helps me (and others) to avoid reinventing the wheel and duplicating existing approaches. It aims to help app developers maximize impact by aiding complementary additionality.

and make high-quality products. If used wisely, money can help build communities of sustainable impact.

#### Define Words

Define every word in the title: "The Journey from Consumer to Investor: Designing a Financial AI Companion for Young Adults to Help with Sustainable Shopping, Savings, and Investing"

-   Journey - behavioral change takes time
-   Consumer, purchase goods without thinking about the effect
-   Investor, thinking about the return
-   Design, decisions
-   Financial, dealing with money
-   AI Companion, automated sidekick
-   College Students
-   Help, be of assistance
-   Sustainable Shopping
-   Savings, in this context I mean Sustainable Savings, that is reducing one's environmental footprint
-   Investing, activity of thinking longer-term

## Research Limitations

-   This work is focused on user experience design and does attempt to make a contribution to economics. Sacred Economics is use as-is as a framework and visualization tool.

-   First, finance is a highly regulated industry and the proposed user experience designs may be limited by legal requirements. This study does not take such limitations into account, rather focusing only on the user experience.

-   Finally, ESG needs data to give us an accurate understanding of the realities inside companies and the user experience design does not address the underlying data quality problem further than by providing a link to the data source.

-   Research Reason: While many people are working on AI models, there's a lack of people working on "Human-AI interaction". Sustainability is the context. How can we better team up to solve the challenges we face this century? The huge externalities.