---
title: Results
bibliography: [ref.bib]
csl: harvard.csl
sidebar_position: 5
editor:
    render-on-save: false
suppress-bibliography: true
---

# Results

## Expected Findings

-   During the preparation of this research proposal, I conducted a preliminary round of face-to-face interviews using 21 open-ended probing questions using a convenience sampling of NCKU students on campus between ages 19 and 29, a total of 12 respondents. The interviews lasted between 9 and 21 minutes and were conducted to get some initial feedback on my research idea, the respondents' daily routines, app usage, feelings towards financial questions, including investing, relationship with nature, and environmental sustainability. These preliminary conversations led me to emphasize more on the financial journey, i.e., to consider the importance of the shopping, savings, and payments apps students already use daily, which could serve as an entry point to becoming an investor. I expect my future research findings to confirm this initial idea and offer diverse ways and examples of what that path could look like in practice.

## Findings

-   Literature: AI assistants should integrate with Digital Product Passports
-   Literature: AI assistants should show carbon label data.
-   Literature: AI assistants should avoid taking ESG at face value (because it's a really low bar) and integrate other metrics such as B Corp.
-   Literature: AI assistants should 

### RQ 1

**How might AI assistants empower regenerative shopping, saving, and investing?**

Display the ESG, EPR, B-Corp, etc, etc credentials for each product and investment.

EPR and B-Corp are success stories which shoul be highlighted while ESG is largely discredited.

There are many existing and ongoing approaches to sustainability. The best approach might be to plug into excisting system and communities and legislation to support and empower them.

### RQ 2

**How might one design an intuitive sustainable shopping, saving, investing app?**

Apple Watch app

### RQ 3

**What app features might college students rate as the highest priority?**

Autopilot

### RQ 4

**How might one visualize ecological impact in digital product design?**

Accuracy is more imprttant for hhuman trust tthan actual impact