---
title: Terminology
bibliography: [ref.bib]
csl: apa.csl
sidebar_position: 8
---


# Terminology

AI - Artificial intelligence, a field of computer science and an umbrella term focused on a wide range of approaches to automation

UX - User experience, a field of study and operational approach focused on how humans experience using systems

AX - Algorithmic experience, a proposed category of user experience, that is focused on interfaces between AI algorithms and humans

UI - User interface, such as in a mobile app, however increasingly audio, video, etc

Fintech - Financial technology, the application of technology (usually AI), to classic financial services, such as payments

ESG - Environmental, Social, and Corporate Governance, a new set of metrics proposed by the European Union, and adopted worldwide, to assess business and financial assets

AI Assistant - software system providing the user with personalized suggestions based on machine learning algorithms

Financial Advisor - a human financial specialist providing customized financial advice, including investment advice and services to a client

ML - Machine learning, a tool within the larger AI umbrella to enable computers to learn from large sets of data, which may be labeled (by humans) or un-labeled (auto-labeled)

HCI - Human-computer interaction, a field of study to improve human experience with information technology

OEM - Original equipment manufacturer, a company making products for another company that markets and sells such products under their own brand

API - Application Programming Interface, a method for software agents to exchange information in various forms of data: the basis for contemporary online services

EPR - Extended Producer Responsibility 

LLM - Large Language Models

CO2e - CO2 equivalent

GHG - Greenhause gases

PD - Participatory Design