```{=mdx}
import Figure from '/src/components/Figure';
import MyEmbed from '/src/components/Embed';
```
```{python}
import warnings
warnings.filterwarnings("ignore")
```

## Research Limitations

First, this work is focused on integrating sustainability into user experience design and does attempt to make a contribution to economics, finance, on any related technical field - in the context of this work, these fields are sources of inspiration for design.

Second, finance is a highly regulated industry and the proposed user experience designs may be limited by legal requirements. This study does not take such limitations into account, rather focusing only on the user experience.

Third, up-to-date ESG data is expensive and thus couldn't directly be used in this research. ESG needs data to give us an accurate understanding of the realities inside companies and the user experience design does not address the underlying data quality problem further than by providing a link to the data source.

Fourth, I don't have access to users' financial data, which would be useful for design research.

Fifth, the student survey only reached less than 50% of the universities in Taiwan. The table below list all the higher education institutions in Taiwan without a single respondent. Hopefully, future work can cover these schools as well.

| County / City | University |
|-------------------|-----------------------------------------------------|
| **Changhua** | 中州科技大學 Chung Chou University of Science and Technology (CCUT) |
|  | 大葉大學 Dayeh University (DYU) |
|  | 建國科技大學 Chienkuo Technology University (CTU) |
| **Chiayi** | 南華大學 Nanhua University (NHU) |
|  | 吳鳳科技大學 WuFeng University (WFU) |
|  | 崇仁醫護管理專科學校 Chung Jen College of Nursing, Health Science and Management (CJC) |
|  | 稻江科技暨管理學院 Toko University (TOKO) |
|  | 大同技術學院 Tatung Institute of Technology (TTC) |
| **Hsinchu** | 中華大學 Chung Hua University (CHU) |
|  | 元培醫事科技大學 Yuanpei University of Medical Technology (YUMT) |
| **Hsinchu** | 明新科技大學 Minghsin University of Science and Technology (MUST) |
| **Hualien** | 臺灣觀光學院 Taiwan Hospitality & Tourism University (THTU) |
|  | 慈濟大學 Tzu Chi University (TCU) |
|  | 慈濟科技大學 Tzu Chi University of Science & Technology (TCUST) |
|  | 大漢技術學院 Dahan Institute of Technology (DIT) |
| **Kaohsiung** | 一貫道天皇學院 I-Kuan Tao College (IKTC) |
|  | 中華民國海軍軍官學校 ROC Naval Academy (CNA) |
|  | 中華民國空軍軍官學校 ROC Air Force Academy (CAFA) |
|  | 中華民國陸軍軍官學校 ROC Military Academy (ROCMA) |
|  | 輔英科技大學 Fooyin University (FYU) |
|  | 高苑科技大學 Kao Yuan University (KYU) |
|  | 高雄市立空中大學 Open University of Kaohsiung (OUK) |
|  | 國立高雄大學 National University of Kaohsiung (NUK) |
|  | 國立高雄餐旅大學 National Kaohsiung University of Hospitality and Tourism (NKUHT) |
|  | 義守大學 I-Shou University (ISU) |
|  | 樹德科技大學 Shu-Te University (STU) |
|  | 正修科技大學 Cheng Shiu University (CSU) |
|  | 東方設計大學 Tung Fang Design University (TFU) |
| **Keelung** | 崇右影藝科技大學 Chungyu University of Film and Arts (CUFA) |
| **Miaoli** | 亞太創意技術學院 Asia-Pacific Institute of Creativity (APIC) |
|  | 仁德醫護管理專科學校 Jen-Teh Jr. College of Medicine, Nursing & Management (JENTE) |
| **Nantou** | 一貫道崇德學院 I-Kuan Tao Chung-De Institute (IKTCDI) |
|  | 南開科技大學 Nan Kai University of Technology (NKUT) |
| **New Taipei** | 亞東科技大學 Asia Eastern University of Science & Technology (AEUST) |
|  | 致理科技大學 Chihlee University of Technology (CLUT) |
|  | 華夏科技大學 Hwa Hsia University of Technology (HWH) |
|  | 華梵大學 Huafan University (HFU) |
|  | 台北基督學院 Christ’s College Taipei (CCT) |
|  | 國立臺灣藝術大學 National Taiwan University of Arts (NTUA) |
|  | 馬偕醫學院 Mackay Medical College (MMC) |
|  | 明志科技大學 Ming Chi University of Technology (MCUT) |
|  | 東南科技大學 Tungnan University (TNU) |
|  | 真理大學 Aletheia University (AU) |
|  | 國立空中大學 National Open University (NOU) |
| **Penghu** | 國立澎湖科技大學 National Penghu University of Science & Technology (NPU) |
| **Pingtung** | 慈惠醫護管理專科學校 Tzu Hui Institute of Technology (TZUHUI) |
| **Taichung** | 中山醫學大學 Chung Shan Medical University (CSMU) |
|  | 中臺科技大學 Central Taiwan University of Science & Technology (CTUST) |
|  | 修平科技大學 Hsiuping University of Science & Technology (HUST) |
|  | 國立勤益科技大學 National Chin-Yi University of Technology (NCUT) |
|  | 國立臺中教育大學 National Taichung University of Education (NTCUED) |
|  | 國立臺中科技大學 National Taichung University of Science & Technology (NTCUST) |
|  | 靜宜大學 Providence University (PU) |
|  | 嶺東科技大學 Ling Tung University (LTU) |
|  | 朝陽科技大學 Chaoyang University of Technology (CYUT) |
|  | 弘光科技大學 Hungkuang University (HK) |
| **Tainan** | 中信金融管理學院 CTBC Business School (CTBC) |
|  | 南榮科技大學 Nan Jeon University of Science & Technology (NJU) |
|  | 敏惠醫護管理專科學校 Min-Hwei College of Health Care Management (MHCHCM) |
|  | 崑山科技大學 Kun Shan University (KSU) |
|  | 國立臺南護理專科學校 National Tainan Junior College of Nursing (NTJCN) |
|  | 康寧大學 University of Kang Ning (UKN) |
|  | 台灣基督長老教會南神神學院 Taiwan Presbyterian Theological Seminary (TPTS) |
| **Taipei** | 中國科技大學 China University of Technology (CUTE) |
|  | 中華福音神學研究學院 China Evangelical Seminary (CES) |
|  | 國立臺北商業大學 National Taipei University of Business (NTUB) |
|  | 國立臺北教育大學 National Taipei University of Education (NTUE) |
|  | 國立臺北護理健康大學 National Taipei University of Nursing & Health Sciences (NTUNHS) |
|  | 國立臺北大學 University of Taipei (UT) |
|  | 國立臺灣戲曲學院 National Taiwan College of Performing Arts (NTCPA) |
|  | 台灣神學研究學院 Taiwan Theological College & Seminary (TTCS) |
|  | 台灣警察專科學校 Taiwan Police College (TPC) |
|  | 大同大學 Tatung University (TTU) |
|  | 國防醫學院 National Defense Medical Center (NDMC) |
|  | 德明財經科技大學 Takming University of Science & Technology (TMUST) |
| **Taoyuan** | 中央警察大學 Central Police University (CPU) |
|  | 南亞技術學院 Nanya Institute of Technology (NANYA) |
|  | 萬能科技大學 Vanung University (VNU) |
|  | 長庚科技大學 Chang Gung University of Science & Technology (CGUST) |
|  | 黎明技術學院 Lee-Ming Institute of Technology (LIT) |
|  | 新生醫護管理專科學校 Hsin Sheng College of Medical Care & Management (HSC) |
|  | 國立體育大學 National Taiwan Sport University (NTSU) |
|  | 國防大學 National Defense University (NDU) |
| **Yilan** | 蘭陽技術學院 Lan Yang Institute of Technology (LYIT) |
|  | 聖母醫護管理專科學校 St. Mary’s Medicine Nursing & Management College (SMC) |
| **Yunlin** | 環球科技大學 TransWorld University (TWU) |
|  | 福智佛教學院 Bliss & Wisdom Buddhist College (BWBC) |

## Future Research

Some ideas for fruitful research directions:

-   Perceptions of pollution levels among Taiwanese college students.

-   Does the specialized interface for AI offer any advantages of a general-purpose UI such as ChatGPT, Claude, Gemini, Mistral, and others?

-   While many people are working on AI models, there's a lack of people working on Human-AI interaction in the context of sustainability.

If you do decide to pursue any of these questions or were otherwise inspired by my thesis, please do reach out. As I have interest in these areas of research, I would be happy to help in any way I can. Thank you.