---
title: College Students
bibliography: [../ref.bib]
csl: ../harvard.csl
sidebar_position: 1
editor:
    render-on-save: false
suppress-bibliography: true
---

## College Students

This research focuses on developing an AI companion for ***college students***.

### Personas

User research makes extensive use of user ***personas*** to represent a group of people with similar attributes. Designers use personas to ***articulate assumptions,*** which is useful for ***user-centered design*** and also to reflect on what kind of ***biases*** might exist in the design. Within the larger cohort of College Students several different personas could be defined, for example grouping people by interests, knowledge, habits, levels of anxiety, and other attributes.

Humans have a long list of cognitive biases, which a good design should take into account.

There is extensive research on the attitudes of U.S. college students towards climate change. @americanpressinstituteKnowingNewsHow2022 reports only 37% percent of U.S. Generation-Z and Millenials follow news related to environmental issues. @schwartzClimateChangeAnxiety2022 reports some adult US students in a small study (18-35, N = 284) express feelings of insignificance of their actions to achieve any meaningful impact. @thomaesGreenTeensUnderstanding2023 reports U.S. adolescents don't find sustainability relevant to their daily life. @rossClimateChangeChallenge2016 says most people in the U.S. don't act on climate change. "Action on climate change has been compromised by uncertainty, aspects of human psychology".

@creditsuisseYoungConsumersMay2022 suggests young consumers are more eco-friendly and drive the speed of change.

-   98% of Gen-Z owns smartphone in comparison to 80% of the general world population [@globalwebindex98GenOwn2017; @bankmycellHowManyPeople2022].

-   @brankavuletaGenerationStatistics2023 gen-z born between 1997 and 2012

-   @deyangeorgiev39SmartphoneStatistics2023

-   The Economist has ran a few anonyomous articles calling gen-z green ideals into question @HowSellYoung2023; @HowGenMillennials2023

-   @alexreiceMostEcoconsciousGeneration2021

The above studies give foundation for creating a persona of a U.S. College Student who doesn't follow environmental news and thinks climate action doesn't make a difference. This doesn't necessarily mean this group of people with similar ideas would deny climate change is happening. Rather "Climate Denier" could be another persona, grouping people into a cohort who thinks climate change is not real. Further research would be needed to define relevant personas which have meaningful predictive and generalizing power.

| Description           | Name  | Beliefs                       |
|-----------------------|-------|-------------------------------|
| Climate Change Denier | Jake  | Climate change doesn't exist. |
|                       | Alice |                               |
|                       | Sam   |                               |

: College Student Personas

-   @crabbRantTerriblePersonas2023

@RooneyVargaClimateActionSimulation2019 shows the effectiveness of ***The Climate Action Simulation*** in educating users about **success scenarios**.

### Social Trust

-   When disaster hits we need high levels of social trust.

### Climate Anxiety

A large @hickmanClimateAnxietyChildren2021 worldwide study (n=10000, aged 16-25) provides evidence the youth is anxious about climate in Australia, Brazil, Finland, France, India, Nigeria, Philippines, Portugal, the UK, and the USA. Similarly, @thompsonYoungPeopleClimate2021 finds young people around the world have climate anxiety. @whitmarshClimateAnxietyWhat2022 shows worry about the climate in the UK is generally widespread (over 40% of the respondents, n=1332), while climate anxiety is highest among young people and is a possible motivator for climate action. Additionally, @ogunbodeClimateAnxietyWellbeing2022 finds climate anxiety in 32 countries and also supports the idea that climate anxiety leads to climate activism. @thibodeauThreeCompaniesClosing2022: "In 2021, the BBC polled 1,000 people in Scotland to understand the barriers to taking climate action. What they found was even though many people were aware of actions needed to take to address climate change, and had intentions to their behaviors didn't change. This is a phenomenon called the intention-action gap."

-   Designing for Health and Sustainability: Health and sustainability are intrinsically connected. @kjaergardHealthSustainability2014 shows how *"understanding health and sustainability as a duality, health both creates conditions and is conditioned by sustainability, understood as economic, social and environmental sustainability, while on the other hand sustainability creates and is conditioned by human health"*

-   Design for Human Rights @unfcccSharmElSheikhImplementation2023 text refers to "human right to a clean, healthy and sustainable environment".

-   Refi podcast: "people need agency".

-   @martiskainenContextualizingClimateJustice2020 (need access)

-   @seabrookMusicTherapyEra2020 (need access)

-   Older research on young adults (Millenials at the time) highlights how Millenials "use Google as a reference point for ease of use and simplicity" @katemoranDesigningYoungAdults2016.

### Embodied Carbon

-   "embodied carbon"
-   Carbon Neutral Cities Alliance
-   @buildersforclimateactionMakingRealZero2021

### Community

Humans working together are able to achieve more than single individuals. "Any community on the internet should be able to come together, with capital, and work towards any shared vision. That starts with empowering creators and artists to create and own the culture they're creating. In the long term this moves to internet communities taking on societal endeavors."

-   Building a culture of sustainability? @lakshmirebeccaManWhoGamifying2018; @armstrongCultivatingCulturesSustainability2021

***Zero Waste Lifestyle*** is the opposite of overconsumption. Zero waste suggests people buy in bulk to save. Buying in bulk for more savings and to reduce packaging. Through group purchases and community investing while also reducing consumption.

***Minimalism*** is a movement of people living a simple life. This is always going to be a small percentage of people. @costaHowFinnishCulture2018: Finnish socialists: minimalism. Tokyo @tokyosimpleecolifeWhatLearnedMy2021.

### Empowerment

-   I would like to have an AI agent to set my requirements and preferences and give a "fuck you" middle finger to companies that don't meet them. I could also give a thumbs up to companies that meet my expectations. Perhaps the user interface could like Tinder where I can swipe left and right.

### Trust

### Memes

-   Coined by Richard Dawkins in 1976 in the context of biology.

-   Internet memes and meme stocks

-   Memes from daily life, business to war, are relevant to penetrating through the noise of the web.

-   Memes and sustainability?

-   Meme research has become an academic discipline

-   Memes have become a popular communication tool..

-   @zidaniMessyInternetMemes2021

-   @zidaniHowConductInternet2022

-   @irinalyanWhenGangnamHits2015

-   @zannettouOriginsMemesMeans2018

-   @peters-lazaroPopularCultureCivic2020

## Designing Industries

It's possible to re-design entire industries and that is exactly the expectation sustainability sets on businesses. Across all industries, there's a call for more transparency. Conversations about sustainability are too general and one needs to look at the specific sustainability metrics at specific industries to be able to design for meaningful interaction. There's plentiful domain-specific research showing how varied industries can develop eco-designed products. I will here focus on 2 industries that are relevant for college students.

### Fashion

Young people are the largest consumers of fast fashion [@YoungConsumersComplicated]. In @europeanenvironmentagencyTextilesEnvironmentRole2022, European Environment Agency (EEA) estimates based on trade and production data that EU27 citizens consumed an average 15kg of textile products per person per year.

Sustainable Fashion, Textile Design

-   There are signs of young Chinese consumers valuing experiences over possessions @jiangHowHaveCovid2023.

-   @millward-hopkinsMaterialFlowAnalysis2023 shows how half of the textile waste in the UK is exported to other countries.

-   Story of Patagonia @chouinardLetMyPeople2005

Across industries, reports are saying there isn't enough transparency.

-   [@hannahritchieSectorSectorWhere2020 @usepaGlobalGreenhouseGas2016] GHG emission inventory by sector

-   **Problem**: @emilychanWeStillDon2022 report says there's not enough transparency in fashion:

-   Fashion greenwashing, fashion is 2%-8% of total GHG emissions, 2.4 Trillion USD industry, 100B USD lost to lack of recycling, contributes 9% of microplastics: @adamkiewiczGreenwashingSustainableFashion2022

-   @centobelliSlowingFastFashion2022 per year uses 9B cubic meters of water, 1.7B tonnes of CO~2~, 92 million tonnes of textile waste.

-   @kohlerCircularEconomyPerspectives2021: Globally 87% of textile products are burned or landfilled after 1st consumer use.

-   @marrucciImprovingCarbonFootprint2020 Italian retail supermarkets carbon footprint?

-   @leungGreenDesign2021 There's a growing know-how on how to produce sustainably and which materials to use. "Handbook of Footwear Design and Manufacture" Chapter 18 - Green design.

-   @emilychanWill2022Be2022 New Standard Institute's proposed "Fashion Act" to require brands doing business in New York City to disclose sustainability data and set waste reduction targets.

-   @wikirateSharingDataCreating2022: "Among the Index's main goals are to help different stakeholders to better understand what data and information is being disclosed by the world's largest fashion brands and retailers, raise public awareness, educate citizens about the social and environmental challenges facing the global fashion industry and support people's activism."

-   @mabuzaNaturalSyntheticDyes2023 shows consumer knowledge of apparel coloration is very limited.

-   @gyabaahCharacterizationDumpsiteWaste2023 research across several dumpsites across Ghana revealed up to 12% of the landfill consisted of textile waste.

-   @imperfectidealistSustainableGreenwashingHow2020 Fashion sustainability vs greenwashing

-   @TransparencySustainabilityPlatform2023 Ethical Shopping

-   @SheepIncSoftcore2023 Ethical brand?

-   @goodonyouGoodYouSustainable2023 Sustainable fashion company evaluations

-   @LilyMindfulActive Garment Worker's rights

-   @emilychanWillFashionIndustry2022: fashion companies can't be held accountable for their actions (or indeed, their lack of action).

-   @wikirateWikiRate2023

-   @InstantGratificationCollective2022: "Political consumerism", "Instant Gratification for Collective Awareness and Sustainable Consumerism"

-   @fashioncheckerFashionCheckerWagesTransparency2023

-   @eestidisainikeskusiestoniandesigncentreCircularDesignHOW2021 Circular textiles

-   @eestikunstiakadeemiaEKAArendasEuroopa2022 Sustainable Fashion education

-   @fashionrevolutionfoundationFASHIONTRANSPARENCYINDEX2022 Fashion transparency index

-   @CleanClothesCampaign

-   "The mainstream fashion industry is built upon the exploitation of labor, natural resources and the knowledge of historically marginalized peoples."

-   @TextileGenesis

-   "Secrecy is the linchpin of abuse of power...its enabling force. Transparency is the only real antidote." Glen Greenwald, Attorney and journalist.

-   @stand.earthStandEarthPeople2023

-   @NewStandardInstitute

-   @BGMEAHome Bangladesh Garment Manufacturers and Exporters Association

-   @errKomisjonTahabVahendada2022 European Commission wants to reduce the impact of fast fashion on EU market.

-   Minimize shopping, buy quality, save CO~2~, invest.

-   @textileexchangeTextileExchange2023 Ethical fashion materials matter

-   @textileexchangeFASHIONINDUSTRYTRADE2021: Policy request

-   Free clothes

-   @vanishukGENERATIONREWEARFull2021 "Generation rewear" documentary, sustainable fashion brands

-   @storbeckFastFashionMust2021 and @remingtonZalandoZignLabel2020: Zalando says Fast fashion must disappear

-   @infinitedfiberInfinitedFiber2023

-   @cleantechgroupGlobalCleantech1002023 Global cleantech 100

-   @SOJODoortodoorClothing2023 Alterations and repairs made easy

-   @GoodYouSustainable2023 Ethical brand ratings

### Food

#### Perennial Crops

-   Multi-year crops reduce inputs of gasoline, labor, etc. @aubreystreitkrugPathwaysPerennialFood2023

-   Large agritech like Monsanto rely on selling seeds annualy for profits, which has lead to farmer suicides when crops fail.

#### Culture, Community, Cuisine, Storytelling

-   @tsingMushroomEndWorld2015 mushrooms

Food is about enticing human imagination and taste buds.

-   Potato used to be a newcomer and innovative crop in Europe, and not it's so common, we forget it's no originally from here.

-   @aubreystreitkrugPathwaysPerennialFood2023 food is also about cuisine and culture; foods become popular if we hear stories and see cuisine around a particular crop.

-   "The agricultural sector contributes to approximately 13.5% of the total global anthropogenic greenhouse gas emissions and accounts for 25% of the total CO~2~ emission" @nabipourafrouziComprehensiveReviewCarbon2023. @pooreReducingFoodEnvironmental2018 suggests 26% of carbon emissions come from food production. @FoodPrints2015 reports dairy (46%) and meat and fish (29%) products making up the largest GHG emission potential. @springmannGlobalRegionalCosts2021 proposes veganism is the most effective decision to reduce personal CO~2~ emissions.

Complex supply chains make seafood (marine Bivalvia, mollusks) logistics prone to fraud, leading to financial losses and threats to consumer health [@santosCurrentTrendsTraceability2023]. The same is true for cocoa beans, which are at risk from food fraud [@fanningLinkingCocoaQuality2023].

-   IARC warns aspartame (artificial sweetener found in many soft drinks) could cause cancer \[CITE\].

<!-- -->

-   @yapLifeCycleAssessment2023 Singapore disposes of 900,000 tonnes of plastic waste out of which only 4% is recycled.
-   @kiesslingWhatPotentialDoes2023 Single-use plastics make up 44-68% of all waste mapped by citizen scientists.

#### Food Waste

There are several initiatives to reduce food waste by helping people consume food that would otherwise be throw away.

```{=mdx}
<Figure caption="ResQ Club saves food waste by selling left-over foods cheaply" src={ResQClub} />
```
| Name                         | Link                                                          |                                                                                                                                                                                |
|----------------------|-------------------------|-------------------------|
| Karma                        | apps.apple.com/us/app/karma-save-food-with-a-tap/id1087490062 |                                                                                                                                                                                |
| ResQ Club                    | resq-club.com                                                 | @kristinakostapLEVITASONAUus2022 ResQ Club in Finland and Estonia for reducing food waste by offering a 50% discount on un-eaten restaurant meals before they are thrown away. |
| Kuri                         |                                                               | @hajejankampsKuriAppThat2022 Less impact of food                                                                                                                               |
| Social media groups (no app) |                                                               |                                                                                                                                                                                |

: Food saving apps

-   @ROOS2023107623 identified 5 perspectives in a small study (*n=106*) of views on the Swedish food system:

| Perspective                         | Content                                                                               |
|--------------------------|----------------------------------------------|
| *"The diagnostic perspective"*      | "*All hands on deck to fix the climate"*                                              |
| *"The regenerative perspective"*    | "*Diversity, soil health and organic agriculture to the rescue"*                      |
| *"The fossil-free perspective"*     | "*Profitable Swedish companies to rid agriculture and the food chain of fossil fuel"* |
| *"The consumer-driven perspective"* | *"A wish-list of healthy, high-quality and climate-friendly foods"*                   |
| "The hands-on perspective"          | "Tangible solutions within the reach of consumers and the food industry"              |

: Perspective on food systems in Sweden.

-   @kommendaWouldCarbonFood2022 Carbon Food Labels

-   Food Sovereignty: "The global food sovereignty movement, which had been building momentum since its grassroots conception in the late '90s, quickly gained traction with its focus on the rights of people everywhere to access healthy and sustainable food. One of the pillars of the movement lies in using local food systems to reduce the distance between producers and consumers."

-   @caitlinstall-paquetFreshCityRise2021: "We can grow foods just as well in the inner city as we can out in the country because we're agnostic to arable land," says Woods. "Because we grow indoors and create our own weather, \[climate change\] doesn't affect our produce."

-   @reneesalmonsenAsiaLargestVertical2018: Vertical farm in Taoyuan

-   @catherineshuSoutheastAsiaFarmtotable2023: *Intensive Farming Practices vs* Farm to table

-   @akshatrathiChrisSaccaReturns2021 and @lowercarboncapitalLowercarbonCapital2023 climate startup funding.

-   Only make what is ordered.

#### Farm to Fork

Farm to fork is a European Union policy to shorten the supply chain from the producer to the consumer and add transparency to the system.

Supply chain innovation in agriculture.

-   Farm to Fork @financialtimesSustainabilityIdeasThat2022

### Construction

-   According to @debnathSocialMediaEnables2022 39% of global CO~2~ emissions comes from the building sector.
-   Construction is large emitter because of the use of concrete; super tall buildings are very CO~2~ intensive [@zhaoEmbodiedCarbonBased2015].
-   embodied carbon
-   @oikosdenktankWebinarDoughnutEconomics2021 circular material procurement requires new skills. How to reuse old paint? Small projects can have large social impact.
-   For example, @DURIEZ2022454 shows how simply by reducing material weight it's possible to design more sustainable transportation.

## Design Implications

-   Community

    -   People exist in relation to other people.

    -   Psychology of 'fundraising clubs' vs individual investing

    -   @UkraineDAOBiddingUkrainian Ukraine DAO to support Ukraine through web3.

    -   These social movements are small and require too much effort to be feasible for the app? Most college students are not zero waste or minimalist.

    -   Group Purchases.

    -   Find Your Composting Community.

    -   Provides a community for pooling money with like-minded investors.

-   Climate Anxiety

    -   How to support the youth? Design to reduce climate anxiety? Is getting people to go to nature more a good way to increase ecological awareness? Empowered by Design. Youth empowerment: The design should empower young people.

    -   Consumer branded carbon credits like angry teenagers?

    -   Invest time not money, student don't have money?

-   Social Trust

    -   **Show Success Scenarios!**

    -   Ask how much time you want to contribute.

    -   Match with other people based on time.

    -   Create a group chatroom.

    -   Use AI to help out with tips.

    -   Ask university students what do they study and match with that industry to become expert and sustainability leader in this field.

    -   People want to help and make a difference. Give people things to do. The @dontlookupMethodology part of the ***Don't Look Up*** movie's social campaign provides 5 user models / roles for the audience to follow: Consumer, Investor, Activist.

    -   Choose Your Climate Solutions.

    -   Younger people show higher motivation (participants in climate protests). How to be relevant for a younger audience?

    -   Yet action remains low.

    -   Targeted and gated to college students.

    -   FB, etc, Gas all had the same launch strategy - start with students

    -   @kuzminskiEcologyMoneyDebt2015 ecology of money

    -   Young people are mobile-first.

    -   Persona: I care mostly about... fashion, art, ...

    -   Young people like to follow trends.

    -   Food ordering apps are popular.

    -   Monoculture -\> regenerative food forests Oil -\> electric cars / bicycles.

    -   Mobile-first.

    -   Social

    -   Educational

    -   Edutainment

    -   Fun

    -   @aespaAespaEseupaMY2020: Karina from Korea. It makes sense your sustainability assistant would talk to you. Studies show gen N is speaking to computers all the time. Interacting with the user is on the rise. For example, Chime makes tipping suggestions on the place of purchase.

    -   The demographics that stand to win the most from the green transformation of business are the youngest generations, with more years of life ahead of them, and more exposure to future environmental and social risks. It would be advisable for Generation Z and their parents (Millennials) to invest their resources in greener assets, however, it's still difficult to pick and choose between 'good' and 'bad' financial vehicles to invest in.

    -   This creates an opportunity for a new generation of sustainable investment apps, focusing on the usability and accessibility of ESG for a mainstream audience. Generation Z and Millennials expect a consumer-grade user experience.

    -   What would that experience look like? I've chosen these demographics with the assumption that if given the right tools, the emotional demand for sustainability could be transformed into action. The exploration of systems of feedback to enable consumers to apply more direct positive and negative pressure to the businesses and consumers signal consequences for undesirable ecological performance is a major motivation of this study.