---
title: Design for Sustainability
bibliography: [../ref.bib]
csl: ../apa.csl
sidebar_position: 1
editor:
    render-on-save: true
---

# Design for Sustainability

## What is Sustainability?
_Sustainability_ was first mentioned in 1713 by *Hans Carl von Carlowitz* in the context of forestry in his seminal book (@hannsscarlvoncarlowitzSylviculturaOeconomicaOder1713) discussing sustainable forest management, today known as *sustainable yield* of *natural capital* required to maintain *ecosystem services* (@peterkareivaNaturalCapitalTheory2011). Contemporary studies have shown *biodiversity* as one key factor to maintain delivery of ecosystem services (@leprovostSupplyMultipleEcosystem2022).

Already @keebleBrundtlandReportOur1988 reported in April 1987 (a few months after I was born) that _'residents in high-income countries lead lifestyles incompatible with planetary boundaries'_. While my home Estonia at the time was considered low-income, a small nation on the verge of poverty behind the Iron Curtain occupation of the Soviet Occupy, we now in 2023, have indeed reached high-income status.

@mobergMobilityFoodHousing2019 reports daily human activites thus on average in France, Germany, Norway and Sweden:

| Emission Share | Category |
|-------|-------------------| 
| 21%   | Housing           | 
| 30%   | Food              | 
| 34%   | Mobility          | 
| 15%   | Other             | 

## Design for Sustainability
**_Designing for Sustainability_** encompasses all human activites, making this pursuit an over-arching challenge across all industries. Assuming that as individuals we want to act in a sustainable way, how exactly would be go about doing that? 

"Global CO2 emissions from energy combustion and industrial processes rebounded in 2021 to reach their highest ever annual level. A 6% increase from 2020 pushed emissions to 36.3 gigatonnes" (@ieaGlobalEnergyReview2022)

Latest figures from the EU's Emissions Database for Global Atmospheric Research (EDGAR) shows (@crippaCO2EmissionsAll2022)

Growing public understanding of how nature works and intersects with our use of money.

The EU Copernicus sattelite system reveals new greenhouse emissions previously undetected (@danielvarjoNyaSatelliterAvslojar2022)

## Digital Product Passports
The European Commision has proposed a *Digital Product Passports* to help companies transfer environmental data (@nissinenMakeCarbonFootprints2022).

## Carbon Emission Labeling
- https://www.climatepartner.com/en/news/labelling-consumer-goods
- https://www.forbes.com/sites/briankateman/2020/07/20/carbon-labels-are-finally-coming-to-the-food-and-beverage-industry/?sh=3fbe47b37c03

## Design for Circularity
- @mcdonoughCradleCradleRemaking2002
- @dullCircularSupplyChain2021

## Population
In November 2022, Planet Earth's population reached 8 Billion people (@theeconomictimesClimateChangeEarth2022) and is projected to reach 8.5B in 2030 and 9.7B in 2050(@unitednationsdepartmentofeconomicandsocialaffairspopulationdivisionWorldPopulationProspects2022). While population growth puts higher pressure on Earth's resources, the effect is more from wasteful lifestyles than the number of people (FIND CITATION).

## Overconsumption, Climate Change, Pollution
Overconsumption is one of the root causes of climate change and marine plastic pollution. @FORD2022150392 and @laversFarDistractionPlastic2022a suggest strong linkage of climate change and marine plastic pollution "along with other stressors that threaten the resilience of species and habitats sensitive to both climate change and plastic pollution".

## Fossil Fuels and Energy
There's evidence from several countries suggesting moving to renewal energy brings benefits:

- @AMIN2022113224 suggests "removing fossil fuel subsidies and intra-sectoral electricity price distortions coupled with carbon taxes provides the highest benefits" for both the economy and the environment in Bangladesh.
- Considerable uncertainty exists among experts which CO2 reduction methods among nature-based and technology-based are the most effective (@lowRethinkingNetZeroSystems2022)

## Make a 'Sustainability Flywheel' graphic, like that of Amazon's
The true cost of products is hidden. The work is hidden.

## Forests
Europe rapidly losing its forest carbon sink:
https://www.euractiv.com/section/climate-environment/news/europe-rapidly-losing-its-forest-carbon-sink-study-shows/

Burning of biomass undermines carbon capture.

## History
Father of climatology Alexander von Humboldt
Isotherms
https://isotherms.simply.earth/?utm_term=FatherOfClimatology
https://medium.com/climate-conscious/2021-047-the-forgotten-father-of-climatology-7c1e709bfcec

## Sustainability
commodities!!
—
the most effective things are
— food
— transport
— fashion?
— plant trees

Bezos. ″‘Good intentions don’t work, mechanisms do’” 
https://www.cnbc.com/2022/10/06/how-this-popular-jeff-bezos-quote-drives-amazons-climate-goals.html

## Disasters
Chernobyl, Exxon Valdez, Deepwater Horizon, the Great Pacific Garbage Patch, and Fukushima

## Scalable Climate Solutions
...

## The State of Nationally Determined Contributions: 2022
https://www.wri.org/research/state-nationally-determined-contributions-2022

## Health
https://www.webmd.com/a-to-z-guides/features/sustainability-health
“Human health is central to all sustainability efforts. “All of these (food, housing, power, and health care), and the stress that the lack of them generate, play a huge role in our health,” Hollis says.”

https://www.ncbi.nlm.nih.gov/books/NBK202304/
https://oxford.universitypressscholarship.com/view/10.1093/acprof:oso/9780199325337.001.0001/acprof-9780199325337
https://www.amazon.com/Health-Sustainability-Introduction-Tee-Guidotti/dp/0199325332

“Sustainability is important for many reasons including: Environmental Quality – In order to have healthy communities, we need clean air, natural resources, and a nontoxic environment.”’
https://www.unthsc.edu/operations/wp-content/uploads/sites/24/Sustainability_Summary_Half_Page_better_pic_1_.pdf

## Emission Scopes
The U.S. National Public Utilities Council (NPUC) utility decarbonization report (@nationalpublicutilitiescouncilAnnualUtilityDecarbonization2022) provides a useful categorizaton of company emissions:
- Scope 1: Direct emissions
- Scope 2: Indirect electricity emissions
- Scope 3: Value chain emissions

## Greenwashing
Greenwashing is a large detractor from environmetal action as it's difficult to know what is sustainable and what is not.

- it’s possible to curb greenwashing!

A number of new AI-based solutions aim to find instancessof greenwashing
https://www.fastcompany.com/90656749/greenwashing-ai
https://www.linkedin.com/in/julian-koelbel/?originalSubdomain=ch
https://www.bf.uzh.ch/en/persons/lambillon-adrien-paul
https://www.climatebonds.net/about/team/krista-tukiainen

https://www.theguardian.com/environment/2022/nov/03/greenwash-home-compostable-plastics-dont-work-aoe?CMP=share_btn_tw
https://www.frontiersin.org/articles/10.3389/frsus.2022.942724/full
https://www.theguardian.com/environment/2019/apr/29/biodegradable-plastic-bags-survive-three-years-in-soil-and-sea

Both the European Commission and the Chair of U.S. Securities and Exchange Commission (SEC) Gary Gensler have called for more legislation to curb business greenwashing practices (@ussecuritiesandexchangecommissionOfficeHoursGary2022). Until new legislation is in place (2030 in the EU), consumer awareness is crucial as currently most emission-reduction programmes are voluntary (@andreVoluntaryCarbonNeutral2022) and thus affected by consumer demand.

- Greenwashing is widespread in company social media communications @geoffreysupranThreeShadesGreen2022

Sometimes greenwashing comes under legislative protection:
- "A recent investigation shows illegal logging of protected areas in eastern European countries that supplies residential wood pellets in Italy. Belgium, Denmark, and the Netherlands are importing pellets from Estonia, where protected areas are logged for pellets and the country has lost its forest carbon sink, despite large-scale wood pellet plants being certified ‘sustainable’ by the Sustainable Biomass Program" (@boothBurningCarbonSink2022)
-- **Possible design implication:** _app could highlight poor legislation refuted by science_.

## Carbon Labelling
Adding CO2 labels for consumer products have been discussed for decades (@adamcornerWhyWeNeed2012). While academic literature has looked at even minute detail such as color and positioning of the label (@zhouCarbonLabelsHorizontal2019) and there is some indication consumers are willing to pay a small premium for low-CO2 products (@xuLowcarbonEconomyCarbon2022) as well as all else being equal, choose the option with a lower CO2 number (@carlssonSustainableFoodCan2022), the idea of _Carbon Labelling_ is yet to find mainstream adoption. 

Although there's some evidence to suggest labeling low CO2 food enables people to choose a _climatarian diet_ in a large-scale study of UK university students, their impact on the market share of low-carbon meals is negible (@lohmannCarbonFootprintLabels2022). @asioliConsumersValuationCultured2022 found differences between countries, where Spanish and British consumers chose meat products with _‘No antibiotics ever’_ over a _Carbon Trust_ label, whereas French consumers chose CO2 labeled meat products. Labels alone are not enough, as underlined by @edenbrandtConsumerPerceptionsAttitudes2022 in Sweden in a study which found a negative correlation between worrying about climate impact and interest in climate information on products, suggesting a need for wider environmental education programmes. 

## Climate Change
- Tipping points @armstrongmckayExceedingGlobalWarming2022

## European Green Deal
https://ec.europa.eu/info/strategy/priorities-2019-2024/european-green-deal_en
https://en.wikipedia.org/wiki/European_Green_Deal
https://www.switchtogreen.eu/the-eu-green-deal-promoting-a-green-notable-circular-economy/

It’s up to legislators to provide sustainable products on our marketplace… but unttiil we do, use tthe green filterr

—-
- One of the eu goals is reducing comsumption
- Tacking your consumption habits

## Minimalism
Finnish socialists: minimalism 
https://www.forbes.com/sites/celinnedacosta/2018/08/30/what-finnish-culture-can-teach-you-about-life-design/

—
china emission trading scheme
https://www.carbonbrief.org/in-depth-qa-will-chinas-emissions-trading-scheme-help-tackle-climate-change/

## Database
most sustainable companies. make a database?
https://growensemble.com/environmentally-friendly-companies/
https://www.themuse.com/advice/companies-making-the-planet-better-2020
https://sustainablog.org/articles/sustainability-focused-companies-out-perform-competitors/
https://earthandhuman.org/most-sustainable-companies/
https://www.forbes.com/sites/samanthatodd/2020/01/21/who-are-the-100-most-sustainable-companies-of-2020/?sh=4b0147ba14a4
https://earth.org/worlds-most-sustainable-companies-in-2021/

-
Europe is the hotbed of sustainabillity
https://www.visualcapitalist.com/most-sustainable-companies/
https://lautrecouleur.com/notable-sustainable-companies-in-florida/
https://www.entrepreneur.com/growing-a-business/its-official-customers-prefer-sustainable-companies/324001

Sustainability is hard. Green Filter helps you find companies that are making a true effort and build closer relationships through shopping, savings, and investing. Green Filter helps you find companies that are making a true effort to become sustainable and build closer relationships through shopping, savings, and investing

## Sustainable Finance
UNEP has identified that if the world is to meet its climate change, biodiversity, and land degradation targets, it needs to close a $4.1 trillion financing gap in nature by 2050. The stakes are higher than ever, biodiversity and nature must be at the forefront of the COP27 climate agenda. 
https://www.unep.org/news-and-stories/press-release/unep-and-green-finance-institute-partner-podcast-series-nature-ahead

“We can and must channel private capital into nature-based solutions. This will require policy and regulatory support, catalytic capital and financial innovation. Ahead of COP27 in Egypt, Financing Nature: COP27 Special will showcase examples of where this is already happening, and discuss what we collectively must do to mobilise capital at scale” said Dr Rhian-Mari Thomas, Chief Executive Officer, GFI.
https://www.greenfinanceinstitute.co.uk/

## Carbon Markets
- “The Emissions Gap Report (EGR) 2021: The Heat Is On shows that new national climate pledges combined with other mitigation measures put the world on track for a global temperature rise of 2.7°C by the end of the century. That is well above the goals of the Paris climate agreement and would lead to catastrophic changes in the Earth’s climate. To keep global warming below 1.5°C this century, the aspirational goal of the Paris Agreement, the world needs to halve annual greenhouse gas emissions in the next eight years. 

If implemented effectively, net-zero emissions pledges could limit warming to 2.2°C, closer to the well-below 2°C goal of the Paris Agreement. However, many national climate plans delay action until after 2030. The reduction of methane emissions from the fossil fuel, waste and agriculture sectors could help close the emissions gap and reduce warming in the short term, the report finds. Carbon markets could also help slash emissions. But that would only happen if rules are clearly defined and target actual reductions in emissions, while being supported by arrangements to track progress and provide transparency.“
https://www.unep.org/resources/emissions-gap-report-2021

- 2022 Emissions Gap report (@unitednationsenvironmentprogrammeEmissionsGapReport2022)

## Biodiversity
United Nations Convention on Biodiversity

## Country Contributions
- Climate action tracker https://climateactiontracker.org/countries/

“triple turn”

lack of transparency

—
call for GOP contributors transparency
https://unfccc.int/process-and-meetings/the-paris-agreement/nationally-determined-contributions-ndcs/nationally-determined-contributions-ndcs/ndc-synthesis-report

## Design for Sustainability
- "Evolution of design for sustainability: From product design to design for system innovations and transitions"

## Inflation Reduction Act
https://www.dailykos.com/stories/2022/10/5/2127204/-Climate-Brief-IRA-s-Uncapped-Tax-Credits-Could-Explode-America-s-Economy?utm_campaign=recent

## Farm to Fork
https://en.wikipedia.org/wiki/List_of_countries_by_greenhouse_gas_emissions_per_person

## Taxonomies
Taxonomy of sustainable activities
https://en.wikipedia.org/wiki/Sustainable_finance

## Five user models / roles
https://storage.googleapis.com/count-us-in-strapi-storage/DLU_CUI_Methodology_64e8b3009e/DLU_CUI_Methodology_64e8b3009e.pdf
https://dontlookup.count-us-in.com/methodology

-- Consumer
-- Investor
-- Activist
-- ..
-- ..

## Carbon Inequality
- "while one-tenth of the global population is responsible for nearly half of all emissions, half of the population emits less than 12% of it" @chancelGlobalCarbonInequality2022

## Sustainable Fashion and Textile Design
European Environment Agency (EEA) estimates based on trade and production data that EU27 citizens consumed an average 15kg of textile products per person per year (@europeanenvironmentagencyTextilesEnvironmentRole2022). Globally 87% of textile products are burned or landfilled after 1st consumer use (@kohlerCircularEconomyPerspectives2021). In Europe, there's large variance between member states when in comes to textile recycling: while Estonia and France are the only EU countries where separate collection of textiles is required by law, in Estonia 100% of the textiles were burned in an incinerator in 2018 while in France textiles are covered by an Extended Producer Responsibility (EPR) scheme leading to higher recovery rates (Ibid). 

Nonetheless, EPR schemes do not guarantee circularity and may instead be designed around fees to finance waste management in linear economy models (@christiansenExtendedProducerResponsibility2021). French EPR scheme was upgraded in 2020 to become more circular (@jacquesvernierExtendedProducerResponsibility2021). In any case, strong consumer legislation (such as EPR) has a direct influence on producers' actions. For example, the Hong Kong Trade Development Council notified textile producers in July 2022 reminding factories to produce to French standards in order to be able enter the EU market: (@hktdcresearchFranceExpandsProducer2022). 

There's a growing know-how on how to produce sustainably and which materials to use. "Handbook of Footwear Design and Manufacture" Chapter 18 - Green design (@leungGreenDesign2021)

Virginijus Sinkevičius, EU Commissioner for the Environment, Oceans and Fisheries, is quoted as describing ecodesign "respects the boundaries of our planet" @europeancommissionGreenDealNew2022

## Food
@FoodPrints2015 reports dairy (46%) and meat and fish (29%) products making up the largest GHG emission potential.

*Intensive Farming Practices*

## Actionable Insights
Translate data into everyday actions the app can suggest.

## Packaging
https://www.sulapac.com/

## Digitalisation
Digital Receipts to be able to track your carbon footprint
https://apps.apple.com/fi/app/receipthero/id1565989681

## Social Cost of Carbon 
carbon price
https://apnews.com/article/science-climate-and-environment-government-politics-4c1e8783694201355f88012079367f27

social cost of carbon
https://en.wikipedia.org/wiki/Social_cost_of_carbon#:~:text=The%20social%20cost%20of%20carbon%20is%20a%20calculation%20focused%20on,CO%202%20(%2FtCO%202).
https://news.stanford.edu/2021/06/07/professors-explain-social-cost-carbon/

- "The (Social Cost of Carbon) SCC measures the additional damage caused by an extra unit of emissions" (@kornekSocialCostCarbon2021; @zhenSimpleEstimateSocial2018) with variations between countries (@tolSocialCostCarbon2019) and regions (@wangMeasurementChinaProvincial2022).

- carbon-neutral economy needs higher CO2 prices (@sternCarbonNeutralEconomy2022)

- oceans play crucial role in carbon capture (@howardPotentialIntegrateBlue2017)

- Carbon prices are highly asymmetric (@ritzGlobalCarbonPrice2022)

- Apart from CO2, reduction of other atmospheric pollutants, such as non-CO2 greenhouse gases (GHGs) and short-lived climate pollutants (SLCPs) is required for climate stability (@linOpportunitiesTackleShortlived2022)

- As shown in the Phillipines by @chengAssessingEconomicLoss2022, with increasing extreme weather events, "businesses are more likely to emerge in areas where infrastructure is resilient to climate hazards" 

- In California, "Wildfires are the second most important source of emissions in 2020" and "Wildfires in 2020 negate reductions in greenhouse gas emissions from other sectors." @jerrettSmokeCaliforniaGreenhouse2022
- Quantifying climate damage (@wangMultimodelAssessmentClimate2022) proposes scenarious of climate damage

## Ecosystem Services
There's evidence paying landovners for the ecosystem services their forests provide may reduce deforestation (@bousfieldCarbonPaymentsCan2022). Estonian startups Arbonic and Single.Earth are trialing this approach in several forests.

- @hanEmbeddingNaturebasedSolutions2022 identifies nature-based ssolutions "land re-naturalization (such as afforestation and wetland restoration)"

- @noriegaResearchTrendsEcosystem2018 attempts to quantify tthe ecosystem services (ES) provided by insects. While it can be assusmed much of the flora and fauna are crucial for Earth's systems, science is still in the process of understanding and quantifying its contributions. Meanwhile the destruction pressure on ecosystems is rapidly increasing (cite A B C).

## Regeneration
https://www.regen.network/
https://blogs.microsoft.com/blog/2021/01/28/one-year-later-the-path-to-carbon-negative-a-progress-report-on-our-climate-moonshot/?fbclid=IwAR3DiYoaCCobb8a0IvYxdzszV6i2QIUMeuqvIidWVkrbX01Nyd7tq-Sq7bI
https://www.youtube.com/watch?v=Pv8OTD-Ze6E&feature=emb_title
https://medium.com/regen-network/intersecting-carbon-markets-and-web3-for-regenerative-change-5a3a24108503?source=collection_home---4------0-----------------------
https://www.klimadao.finance/
https://rss.com/podcasts/potk/367282/
https://members.delphidigital.io/reports/a-peak-into-the-cosmos-ecosystem/

## Biodiversity
- Number of species killed, mass destruction of nature. "69% decline in the relative abundance of monitored wildlife populations around the world between 1970 and 2018. Latin
America shows the greatest regional decline in average population abundance (94%), while freshwater species populations have seen the greatest overall global decline (83%)." (@almondr.e.a.LivingPlanetReport)

- The Convention on Biodiversity 2022 (COP15) adopted the first global biodiversity framework to accompanpy climate goals (*ADD CITATION*). 

## Air Pollution
@bouscasseDesigningLocalAir2022 finds strong health and economic benefits across the board from air pollution reduction in France.

Grounbreaking research by @lim1MOAirPollutioninduced2022 analysed over 400000 individuals in England, South Korea and Taiwan establishes exposure to 2.5μm PM (PM2.5) air pollution as a cause for lung cancer. 

- Prof Tony Mok, of the Chinese University of Hong Kong: “We have known about the link between pollution and lung cancer for a long time, and we now have a possible explanation for it. As consumption of fossil fuels goes hand in hand with pollution and carbon emissions, we have a strong mandate for tackling these issues – for both environmental and health reasons.” (@hannahdevlinCancerBreakthroughWakeup2022)

*Design*: _People live in the polluted areas are so used to it. What app to wake them up? “You live in a highly polluted area. Here’s what you can do”_

## Supply Chains
Several startups are using distributed ledgers (blockchains) to track source material to the factories ad product movements from factories to markets. While blockchains enable securely tracing data, which is immutablet (no possible to change the same record, only update data in new records), the system still relies on correct data input. As the saying goes, "garbage in, garbage out". Indeed, the blockchain is most useful for auditing, as the time and place of data input can be guaranteed, it will be easier to conduct a search on who inpputted incorrect data.

The blockchain supply chain companies as of October 2022 include:

| №   | Company                                                                       | Link                                     |
| --- | ------------------------------------------------------------------------------ | ------------------------------------------- |
| 1   | Ocean Protocol         | https://oceanprotocol.com/     |
| 2   | Provenance | https://www.provenance.io/                                    |
| 3   | Ambrosius     | https://ambrosus.io/ |
| 4   | Modum     | https://www.modum.io/ |
| 5   | OriginTrail     | https://origintrail.io/ |
| 6   | VeChain     | https://www.vechain.org/|
| 7   | Wabi     | https://wabi.io/ |

Another aspect of supply tracing is the treatment of workers and working conditions. Companies that intend to 2give supply chain a voice" by connecting workers directly to the consumer (even in anonymously, to protect the workers from retribution), include *CTMFile* and *Alexandria*.

https://www.taeltech.com/
https://golden.com/wiki/WaltonChain_(cryptocurrency)-EAVDZX4
https://www.bext360.com/
https://fairfood.org/en/blockchain/

The International Maritime Organization (IMO) targets cutting CO2e emissions in shipping 50% by 2050 compared to 2008 (@matthewgoreEmissionsRegulationsShipping2022).

## Traceability
“uniform traceability system for the entire supply chain.”
https://www.worldwildlife.org/stories/why-tracing-seafood-from-sea-to-plate-is-the-next-frontier-in-sustainability

help consumers to demand more

supply chain
https://www.prima.trade/post/supply-chain-finance-upgrade
https://www.altfi.com/article/2857_fintech_lending_whose_lunch_are_you_eating
https://www.altfi.com/people/tim-nicolle
https://www.prima.trade/faq

give supply chain a voice by connecting workers directly to the consumer
https://www.youtube.com/watch?v=XaNiqDJi7sE
https://ctmfile.com/demos/view/13077
https://ctmfile.com/story/real-time-esg-data-on-supply-chains-a-breakthrough
https://www.es3g.com/post/worker-voice
https://finance.yahoo.com/news/real-time-esg-tracking-stocksnips-160211861.html
https://insight.factset.com/resources/at-a-glance-alexandria-real-time-esg

—
## Realtime ESG
- Instant sustainability impact from supply chain https://techcrunch.com/2022/10/18/makersite-lands-18m-to-help-companies-manage-product-supply-chains/

- Product sustainability modeling https://makersite.io/product-sustainability/

- “Real-time ESG data is more difficult to greenwash”, “supply chain is a significant source of ESG content” (@timnicolleRealtimeESGData)

There's a growing number of companies helping businesses to measure CO2e emissions in their product lifecycle.

FlowIT

Automate CO2 calculations realtime:

https://www.ituudised.ee/uudised/2022/09/22/eesti-it-firma-automatiseeris-flowiti-ja-pwc-toel-susiniku-jalajalje-kaardistamise-saast-90

“factory social score”.

People working at the factories can report conditions

“But the real breakthrough is how we can surface that real-time ESG data directly to individuals in the shops and online, linked to the products that they are browsing and potentially buying. This means that ESG change will finally be driven by the ultimate judge of business success – the customer.”

https://www.esganalytics.io/

## Circular Supply Chains
https://greendice.com/for-a-company/
circular economy for pcs
https://arileht.delfi.ee/artikkel/120071926/kestlikkuse-suunanaitajad-saadavad-teisele-ringile-maja-ja-mobiiltelefoni

—
recycle your phone:
https://arileht.delfi.ee/artikkel/120071926/kestlikkuse-suunanaitajad-saadavad-teisele-ringile-maja-ja-mobiiltelefoni

## Carbon Capture
- @vitilloRoleCarbonCapture2022
- @gaureTrueNotTrue2022: "98% of total electricity production is generated by wind power and solar; the remainder is covered by a backup technology."

—
Cleaning up the supply chain

..
track shipping chain
https://origintrail.io/

—-
suku makee supply changs more transpareent
https://techcrunch.com/2019/01/22/citizens-reserve-is-building-a-supply-chain-platform-on-the-blockchain/
https://www.youtube.com/c/SUKUecosystem/videos

https://finance.yahoo.com/news/traceability-solution-suku-avery-dennison-130000822.html

- make commerce more transparent

IMportant::: “creating sustainbility trust in companies in realtime”
esg blockchains:
https://insights.physisinvestment.com/blockchain-in-esg-investing/
https://jpt.spe.org/blockchain-companies-team-up-to-track-esg-data
https://home.kpmg/xx/en/home/insights/2020/05/creating-trust-in-esg-data.html
https://chiefexecutive.net/why-blockchain-can-both-promote-esg-and-accelerate-climate-transition/
https://www.telos.net/esg-blockchain

—
improve product provenance, blockchains offerr this transparncy

## Factories
—
https://www.ecotextile.com/2018101123789/materials-production-news/world-s-first-free-digital-map-of-apparel-factories-2.html

--

- Tracing emissions from factory pipes.

factory compliacen
Fair Factories
https://www.fairfactories.org/

transparency about the pollutiong factories where the products come from.. the proudct journey

Planet Factory

—
source of plastic waste
https://sourceofplasticwaste.org/

## Internet of Things (IoT)
“thanks to other emerging technology like IoT sensors (to collect ESG data) and blockchain (to track transactions), we have the infrastructure to collect more data, particularly for machine consumption. By measuring real-time energy usage, transportation routes, manufacturing waste, and so forth, we have more quantifiable ways to track corporations’ environmental performance without relying purely on what they say.”

https://www.fastcompany.com/90656749/greenwashing-ai
https://www.asianinvestor.net/article/how-ai-can-help-instos-spot-green-washing/465973
https://planethome.eco/

## Shopping Design
Recycled clothing maker FREITAG offers sustainability-focused services such ass cargo bikes so you can transport your purchases and a network for *shopping without payment* = swapping your items with other members, as well as repairs of their products (@CargoBikeFREITAG).

## Synthesise
*Design Implication*: Your shopping products mostly come from Protector and Gamble (3x) and Nestle. These are large conglemerates with a massive CO2 footprint. See the index to find some alternatives.

## Personas
Use personas to articulate assumptions

Persona: i care mostly about… fashion, art, plap

## Data-Driven Design
Rebuilt the app as a personalized, narrative lifestyle feed

## Design for Recycling
https://www.fastcompany.com/90772025/fast-tech-is-unsustainable-the-circular-economy-is-the-smart-answer-for-growth
“rethinking product design and inspiring consumers to expect more from their devices”

“design is a tool to make complexity comprehensible” like the helsinki chapel. there’s either or a priest or a social worker. it’s the perfect public service. “limit the barrier of entry for people to discover”. elegant.

https://instagram.com/zeynep_von_flittner?igshid=YmMyMTA2M2Y=


## Design Systems
Create a design system!!!! best to showcase my analytic skills

https://www.invisionapp.com/inside-design/guide-to-design-systems/
https://www.designbetter.co/design-systems-handbook
https://design.google/library/google-design-leadership-margaret-lee/
https://atomicdesign.bradfrost.com/

## Community's Role in Design
- Psychology of ‘fundraising clubs’ vs individual investing https://www.partybid.app/party/0x4508401BaDe71aE75fE70c97fe585D734f975502

- POAPs: https://cryptobriefing.com/what-are-poaps-and-why-should-you-collect-them/#:~:text=POAP%20(pronounced%20poh%2Dap),to%20be%20at%20the%20event.

## Group Purchases
through group purchases and community investing while also reducing consumption


People want to help and make a difference. Give people things to do.

Choose Your Climate Solutions

Find Your Composting Community

Monoculture -> regenerative food forests
Oil -> electri cars / bicycles


## Design Studies
eminent journal Design Studies, 1stt design journal
https://reader.elsevier.com/reader/sd/pii/S0142694X16300631?token=8B3FA37DD29295180E82D3B783D5B71E5EF618BEA645403EB62621DFAF1D83FEBE3ADAE17651EB1DB29DEAD1475F1BEE&originRegion=eu-west-1&originCreation=20221015232216

- "Evolution of design for sustainability: From product design to design for system innovations and transitions"

## Eco-Design
“On 30 March 2022, the European Commission put forward a proposal for a regulation establishing a general framework for setting ecodesign requirements for sustainable products, repealing rules currently in force which concentrate on energy-related products only.” (@europeanparliamentEcodesignSustainableProducts2022)

- @MANZARDO2021149507
- @INARRA2022100727
- @MUNARO2022566
- @BASSANI2022151565
- @DURIEZ2022454
- @VANDOORSSELAER2022189
- @DELAPUENTEDIAZDEOTAZU2022718
- @NUEZ2022133252
- @ROSSI2022823
- @TIERNAN2022169
- @ARRANZ2022131738
- @CHEBA2022108601
- @RUIZPASTOR2022130495
- @MIYOSHI2022267

Again, AI has the potential to provide the parameters for sustainability.

- @singhArtificialNeuralNetwork2023 proposes an AI tool for deciding the suitable life cycle design parameters. 

## Circular Economy
@circleeconomyCircularityGapReport2022 reports only 8.6% of world economy is circular and *100B tonnes of virgin materials* are sourced every year.


vaheta oma mööbel
https://www.facebook.com/SMARTSWAP

## Social Objects
I'm interested in the concept of a "social object" https://medium.com/we-research-and-expriment-with-how-the-sharing/what-is-a-social-object-8dd52df0f15c and how the design can connect people to sustainable outcomes while shopping and investing. Perhaps even forming a community of sustainable action. What I showed in class looks like an app but it could also be a physical object (a speculative design). From the presentations I saw most students seemed to be interested in form and light (many lamps) and a couple were about medical uses. I don't remember seeing one that could be compatible with the environmental sustainabilty focus unfortunately...

—
what percent of all design is “sustainable design” ? promoting sustainable design

## Visualise CO2
check carbon impact
https://wizzair.chooose.today/?utm_source=banner&utm_medium=homepage&utm_campaign=wizz&utm_content=calculate-footprint#scrollTo=wtarinhvhtzfdanlnw6qqo

## Designing for Health and Sustainability
Health and sustainability are instriscially connected. _“By understanding health and sustainability as a duality, health both creates conditions and is conditioned by sustainability, understood as economic, social and environmental sustainability, while on the other hand sustainability creates and is conditioned by human health.”_ (@kjaergardHealthSustainability2014)

## Transparency by Design

https://www.youtube.com/watch?v=D2DUMSAsqe0
Data Sharing Archetypes
- 1 Transparency Accountability Advocate
- 2 Compliance Data Aggregator
- 3 Data Intelligence Hub
- 4 Worker Voice Tool
    - https://www.tsgn.org/en/focus-areas/activities/worker-connect
- 5 traceabilityy tooll
    - https://trustrace.com/
- 6 OPen data platform
- 7 knowledge sharing platform
    - https://www.business-humanrights.org/en/


    | №   | Company                                                                       | Link                                     |
| --- | ------------------- | ------------------------------------------- |
| 1   | Ocean Protocol         | https://oceanprotocol.com/     |

WikiRate
OpenData
Transpareencyy
https://www.linkedin.com/in/laureen-van-breen-67b23056/
https://wikirate.medium.com/introducing-the-facility-checker-a-new-search-tool-uncovering-living-wage-gaps-in-fashion-supply-586203aa2998
https://chainreact.org/


swedish open data portal
https://www.dataportal.se/en


Make open data easy to use in everyday life

## Interface Studies
Head of Product Design at Webflow (@davidhoangCreatingInterfaceStudies2022) suggests taking cues from art studies to _isolate the core problem_. "An art study is any action done with the intention of learning about the subject you want to draw". As a former art student, Hoang looks at an interface as _"a piece of design is an artwork with function"_.

## Traceability
200 million pcs sold every yeear
personalized ai, meta glasses understand your context. sense and reconstruct the world around you and to understand the context in which you’re using your device.sense and reconstruct the world around you and to understand the context in which you’re using your device.make suggestions and take action proactively to help you get things done — ideally, so seamlessly that you may not even notice.neuroscience co-adaptation of the interface. your future devices will learn and adapt to you as you use them.

https://tech.fb.com/ar-vr/2022/10/meta-research-reality-labs-connect-2022/

app shows traceability!!

https://www.worldwildlife.org/stories/why-tracing-seafood-from-sea-to-plate-is-the-next-frontier-in-sustainability


## Speculative Design
The question on the intersection of user experience design and speculation have been termed _'speculative design'_ by Anthony Dunne and Fiona Raby in their seminal book (@anthonydunneSpeculativeEverything2013). Speculative design makes use of future scenarios to envision contexts and interactions in future use. Phil Balagtas, founder of The Design Futures Initiative at McKinsey, discusses the value of building future scenarios at his talk at Google (Google Design, 2019). One of his examples, the Apple Knowledge Navigator, from an Apple vision video in 1987, took two decades to materialize in the real world, inspired by a similar device first shown in a 1970s episode of Star Trek as a magic device (a term from participatory design), which then inspired subsequent consumer product development - and then another 2 decades, until the launch of the iPhone in 2007 - a total of 40 years!

In our investment AI advisor app's scenario, the AI is scanning for opportunities matching the user's sustainable investment appetite and risk profile, using different methods of analysis, including alternative data sources. Traditionally, financial analysts only looked at traditional data, such as company reports, government reports, historic performance, etc., for preparing advisory guidance to their clients. With the advent of AI and big data analysis, many other options of researchable data have become available, for example, accurate weather predictions for agriculture can affect guidance, because of expected future weather disasters in the area. Other examples include policy predictions, pollution metrics, etc.

Professional financial advisors use automated tools to analyze data and present it in human form to clients. Today's ubiquitous mobile interfaces, however, provide the opportunity to 'cut out the middleman' and provide similar information to clients directly, at a lower cost and a wider scale, often without human intervention. Additional (more expensive) "human-judgment- as-a-service", a combination of robots + human input, can help provide further personalized advice for the consumer, still at a cheaper price than a dedicated human advisor. Everyone can have a financial advisor. 

“Speculative Design” for a sustainability assistant  

- @BARENDREGT2021374
- @googledesignDesignSpeculativeFutures2019
- @anthonydunneSpeculativeEverything2013

— all green categories
— Green hub
— Ask the user to prioritize

Neri Oxman, biomaterials MIT media lab, 15. sept. 2020
—

Neri Oxman's expressions:
“ecology-indifferent”
“naturing”“mother naturing”
“design is a practice of letting go of all that is unneccesary”
“nature should be our single client”

speculative design
use imagination

- Societal movements change things: implication for design: build a community
- Processes sustain things: implication for design: built an app

## Experience Design
“People buy experiences, not technology.”

—
Loaning terminology from service design, the user journey within an app needs to consider about touchpoint on the way to a state of success. 

Mobile App Design
There's a number of user interface design patterns that have provide successful across a range of social media apps, copied from one to another, to the extent that the largest social media apps share a similar look and feature set.

Mobile-first
Provides a community for pooling money with like-minded investors
Social
Educational
Edutainment
Fun
Stories section like IG / app store
Common UI parts. Feed. Stories.  By using common UI parts from social media users have an easier time to accept the innovative parts. add Viz charts. Avatars are increasingly common and new generations are used to talking to computers. Karina from Korea(aespa, 2020). It makes sense your sustainability assistant would talk to you. Studies show gen N is speaking to computers all the time.
Interacting with the user is on the rise. For example, Chime makes tipping suggestions on the place of purchase.

## Nudge

The literature on _nudge_ is wide, as researches try to find ways to affect human behavious towards sustainability. Some notable examples:
- @ERIKSSON2023229
- @ACUTI2023122151
- @PEREZCUETO2021100346
- @WEE2021100364
- @GUATH2022101821
- @BERGER2022134716

Google and X have offered the “Green Filter” on Maps, Flights, etc. What if there was a “Green Filter” on every product everywhere?

### The Concept of 'Nudge'
One example of _nudge_ are the small UI updates released by Google across its portfolio of products: Google Flights and Google maps. Google's research introduces the concept of _digital decarbonisation_, defined as "Maximising the enabling role of digital technologies by accelerating already available digital solutions" (@implementconsultinggroupHowDigitalSector2022). Google's Chief Sustainability Officer Kate Brandt suggests "Digital solutions play an important enabling role for at least 20-25% of the reductions required to achieve a net-zero economy in Europe" (@katebrandtGoogleClimateAction2022).

| №   | Product  | Nudge  |     
| --- | ------------|-----------|
| 1   | Google Maps        |   Show routes with lower CO2 emissions   |
| 2   | Google Flights      |   Show CO2 emissions       |


“Google recently shared its goal to help one billion people make more sustainable choices by embedding carbon emissions information into Google Flights and surfacing whether a hotel is Green Key or EarthCheck certified.”
https://medium.com/googleplaydev/becoming-a-sustainability-aware-app-or-game-b256803dec93
https://blog.google/outreach-initiatives/sustainability/sustainability-2021/
https://blog.google/outreach-initiatives/sustainability/google-sustainability-summit-2022/
https://blog.google/products/google-nest/nest-renew-general-availability/
https://www.climatiq.io/
https://cloud.google.com/carbon-footprint
https://earthcheck.org/
https://lfca.earth/members/
https://spaceapegames.com/green
https://ghgprotocol.org/
https://www.unep.org/resources/publication/playing-planet-annual-impact-report

## Conclusion
A wide range of legislative proposals, targets, organisations, and goals already exists across Europe. Upcoming laws will harmonize approaches to sustainability and raise standards for all members countries, in turn influencing producers who wish to sell in the EU common market. In unison, the reviewed technologies and practices move us closer to enabling *realtime ESG*: up-do-date transparent information about how our product are produced. Realtime ESG is neccesarly a building block to enable consumers and investors make more accurate, real-world purchase decisions.

# References