---
title: Supply Chains
bibliography: [../ref.bib]
csl: ../apa.csl
sidebar_position: 9
---

# Supply Chains

Several startups are using distributed ledgers (blockchains) to track source material to the factories ad product movements from factories to markets. While blockchains enable securely tracing data, which is immutablet (no possible to change the same record, only update data in new records), the system still relies on correct data input. As the saying goes, "garbage in, garbage out". Indee, the blockchain is most useful for auditing, as the time and place of data input can be guaranteed, it will be easier to conduct a search on who inpputted incorrect data.

The blockchain supply chain companies as of October 2022 include:


| №   | Company                                                                       | Link                                     |
| --- | ------------------------------------------------------------------------------ | ------------------------------------------- |
| 1   | Ocean Protocol         | https://oceanprotocol.com/     |
| 2   | Provenance | https://www.provenance.io/                                    |
| 3   | Ambrosius     | https://ambrosus.io/ |
| 4   | Modum     | https://www.modum.io/ |
| 5   | OriginTrail     | https://origintrail.io/ |
| 6   | VeChain     | https://www.vechain.org/|
| 7   | Wabi     | https://wabi.io/ |



Another aspect of supply tracing is the treatment of workers and working conditions. Companies that intend to 2give supply chain a voice" by connecting workers directly to the consumer (even in anonymously, to protect the workers from retribution), include *CTMFile* and *Alexandria*.






https://www.taeltech.com/
https://golden.com/wiki/WaltonChain_(cryptocurrency)-EAVDZX4
https://www.bext360.com/
https://fairfood.org/en/blockchain/


—

instant sustainability impact from supply chain
https://techcrunch.com/2022/10/18/makersite-lands-18m-to-help-companies-manage-product-supply-chains/
product sustainability modeling
https://makersite.io/product-sustainability/


—
“uniform traceability system for the entire supply chain.”
https://www.worldwildlife.org/stories/why-tracing-seafood-from-sea-to-plate-is-the-next-frontier-in-sustainability

help consumers to demand more

supply chain
https://www.prima.trade/post/supply-chain-finance-upgrade
https://www.altfi.com/article/2857_fintech_lending_whose_lunch_are_you_eating
https://www.altfi.com/people/tim-nicolle
https://www.prima.trade/faq

give supply chain a voice by connecting workers directly to the consumer
https://www.youtube.com/watch?v=XaNiqDJi7sE
https://ctmfile.com/demos/view/13077
https://ctmfile.com/story/real-time-esg-data-on-supply-chains-a-breakthrough
https://www.es3g.com/post/worker-voice
https://finance.yahoo.com/news/real-time-esg-tracking-stocksnips-160211861.html
https://insight.factset.com/resources/at-a-glance-alexandria-real-time-esg

—
## Realtime ESG
https://ctmfile.com/story/real-time-esg-data-on-supply-chains-a-breakthrough
“supply chain is a significant source of ESG content”
“Real-time ESG data is more difficult to greenwash”

“factory social score”.

People working at the factories can report conditions

“But the real breakthrough is how we can surface that real-time ESG data directly to individuals in the shops and online, linked to the products that they are browsing and potentially buying. This means that ESG change will finally be driven by the ultimate judge of business success – the customer.”

https://www.esganalytics.io/

## Circular Supply Chains

—
https://greendice.com/for-a-company/
circular economy for pcs
https://arileht.delfi.ee/artikkel/120071926/kestlikkuse-suunanaitajad-saadavad-teisele-ringile-maja-ja-mobiiltelefoni

—
recycle your phone:
https://arileht.delfi.ee/artikkel/120071926/kestlikkuse-suunanaitajad-saadavad-teisele-ringile-maja-ja-mobiiltelefoni


—
Cleaning up the supply chain

..
track shipping chain
https://origintrail.io/

—-
suku makee supply changs more transpareent
https://techcrunch.com/2019/01/22/citizens-reserve-is-building-a-supply-chain-platform-on-the-blockchain/
https://www.youtube.com/c/SUKUecosystem/videos

https://finance.yahoo.com/news/traceability-solution-suku-avery-dennison-130000822.html

make commerce more transparent

IMportant::: “creating sustainbility trust in companies in realtime”
esg blockchains:
https://insights.physisinvestment.com/blockchain-in-esg-investing/
https://jpt.spe.org/blockchain-companies-team-up-to-track-esg-data
https://home.kpmg/xx/en/home/insights/2020/05/creating-trust-in-esg-data.html
https://chiefexecutive.net/why-blockchain-can-both-promote-esg-and-accelerate-climate-transition/
https://www.telos.net/esg-blockchain

—
improve product provenance, blockchains offerr this transparncy

## Factories
—
https://www.ecotextile.com/2018101123789/materials-production-news/world-s-first-free-digital-map-of-apparel-factories-2.html

facttories

--

Tracing emissions from factory pipes.

—

factory compliacen
Fair Factories
https://www.fairfactories.org/


transparency about the pollutiong factories where the products come from.. the proudct journey

Planet Factory


—
source of plastic waste
https://sourceofplasticwaste.org/

—
iot

“thanks to other emerging technology like IoT sensors (to collect ESG data) and blockchain (to track transactions), we have the infrastructure to collect more data, particularly for machine consumption. By measuring real-time energy usage, transportation routes, manufacturing waste, and so forth, we have more quantifiable ways to track corporations’ environmental performance without relying purely on what they say.”
https://www.fastcompany.com/90656749/greenwashing-ai
https://www.asianinvestor.net/article/how-ai-can-help-instos-spot-green-washing/465973
https://planethome.eco/
https://www.asianinvestor.net/article/how-ai-can-help-instos-spot-green-washing/465973

—

## Conclusion

In unison, the technologies and practices reviwed above move us closer to enabling *realtime ESG*: up-do-date transparent information about how our product are produced. Realtime ESG is neccesarly a building block to enable consumers and investors make more accurate, real-world purchase decisions.
