---
title: Design for Young Adults
bibliography: [../ref.bib]
csl: ../apa.csl
sidebar_position: 4
---

# Population

8 Billion people on the planet as of writing.

# Storytelling and Narrative Design

Bring together film school experience with design...

Does branding also go here?

| №   | Company                                                                       | Link                                     |
| --- | ------------------- | ------------------------------------------- |
| 1   | Ocean Protocol         | https://oceanprotocol.com/     |


Older research on young adults (Millenials at the time) highlights how Millenials "use Google as a reference point for ease of use and simplicity" (@katemoranDesigningYoungAdults2016). The rising availability of AI assistants however may displace Google search with a more conversational UX. Indeed, Google itself is working on smarter tools to displace their own main product, as exemplified by Google Assistant and large investments into LLMs.
 
## Stickyness

## Community


“Any community on the internet should be able to come together, with capital, and work towards any shared vision. That starts with empowering creators and artists to create and own the culture they’re creating. In the long term this moves to internet communities taking on societal endeavors.”
https://www.tradingcardsarecoolagain.com/#toc
https://stockx.com/news/new-balance-no-vacancy-inn-ipo-recap/
https://techcrunch.com/2021/10/25/marcy-venture-partners-cofounded-by-jay-z-just-closed-its-second-fund-with-325-million/
https://techcrunch.com/2021/07/26/queenly-a16z-seed-extension/
https://fortune.com/2020/04/23/digital-art-blockchain-online-galleries/


## References