```{python}
from data.demographics import student_counts, student_age_ranking, university_ranking_table, field_of_study_ranking, mbti_ranking
from data.personas import mbti_introverts_vs_extroverts
import warnings
warnings.filterwarnings("ignore")
```

## Respondent Demographics

### Survey Administration Across Taiwan (October 2023–March 2025)

The responses span from October 2023 to March 2025, covering about 1 year and 5 months of data collection.

| County | University | Responses |
|:-----------------------|:-----------------------|-----------------------:|
| **Changhua** | 國立彰化師範大學 National Changhua University of Education (NCUE) | 2 |
|  | 明道大學 MingDao University (MDU) | 1 |
| **Chiayi** | 國立中正大學 National Chung Cheng University (CCU) | 5 |
|  | 國立嘉義大學 National Chiayi University (NCYU) | 2 |
| **Hsinchu** | 國立清華大學 National Tsing Hua University (NTHU) | 3 |
|  | 玄奘大學 Hsuan Chuang University (HCU) | 1 |
| **Hualien** | 國立東華大學 National Dong Hwa University (NDHU) | 78 |
| **Kaohsiung** | 國立高雄師範大學 National Kaohsiung Normal University (NKNU) | 16 |
|  | 國立高雄科技大學 National Kaohsiung University of Science and Technology (NKUST) | 4 |
|  | 高雄醫學大學 Kaohsiung Medical University (KMU) | 3 |
|  | 國立中山大學 National Sun Yat-sen University (NSYSU) | 2 |
|  | 文藻外語大學 Wenzao Ursuline University of Languages (WZU) | 1 |
|  | 樹人醫護管理專科學校 Shu Zen College of Medicine and Management (SZMC) | 1 |
| **Keelung** | 國立臺灣海洋大學 National Taiwan Ocean University (NTOU) | 3 |
|  | 經國管理暨健康學院 Ching Kuo Institute of Management and Health (CKIMH) | 2 |
|  | 國立臺灣海洋大學 National Taiwan Ocean University (NTOU) | 3 |
| **Taipei** | 國立臺灣大學 National Taiwan University (NTU) | 166 |
|  | 世新大學 Shih Hsin University (SHU) | 28 |
|  | 國立政治大學 National Chengchi University (NCCU) | 17 |
|  | 實踐大學 Shih Chien University (USC) | 14 |
|  | 東吳大學 Soochow University (SCU) | 1 |
|  | 中華科技大學 China University of Science and Technology (CUST) | 1 |
| **Taitung** | 國立臺東大學 National Taitung University (NTTU) | 39 |
|  | 國立臺東專科學校 National Taitung Junior College (NTC) | 1 |
| **Taichung** | 逢甲大學 Feng Chia University (FCU) | 81 |
|  | 國立中興大學 National Chung Hsing University (NCHU) | 17 |
|  | 僑光科技大學 Overseas Chinese University (OCU) | 15 |
|  | 東海大學 Tunghai University (THU) | 8 |
|  | 亞洲大學 Asia University (AU) | 7 |
|  | 弘光科技大學 Hungkuang University | 6 |
|  | 靜宜大學 Providence University (PU) | 5 |
| **Taoyuan** | 銘傳大學 Ming Chuan University (MCU) | 212 |
|  | 開南大學 Kainan University (KNU) | 23 |
|  | 國立中央大學 National Central University (NCU) | 10 |
|  | 元智大學 Yuan Ze University (YZU) | 2 |
|  | 長庚大學 Chang Gung University (CGU) | 1 |
|  | 健行科技大學 Chien Hsin University of Science and Technology (UCH) | 1 |
|  | 中原大學 Chung Yuan Christian University (CYCU) | 1 |
| **Tainan** | 國立成功大學 National Cheng Kung University (NCKU) | 271 |
|  | 長榮大學 Chang Jung Christian University (CJCU) | 42 |
|  | 崑山科技大學 Kun Shan University | 9 |
|  | 南臺科技大學 Southern Taiwan University of Science and Technology (STUST) | 8 |
|  | 嘉南藥理大學 Chia Nan University of Pharmacy and Science (CHNA) | 3 |
|  | 大仁科技大學 Tajen University (TAJEN) | 2 |
|  | 台灣首府大學 Taiwan Shoufu University (TSU) | 1 |
| **New Taipei** | 輔仁大學 Fu Jen Catholic University (FJU) | 243 |
|  | 淡江大學 Tamkang University (TKU) | 57 |
|  | 中國文化大學 Chinese Culture University (CCU) | 35 |
|  | 中華科技大學 China University of Science and Technology (CUST) | 25 |
|  | 龍華科技大學 Lunghwa University of Science and Technology (LHU) | 19 |
|  | 弘光科技大學 Hungkuang University | 0 |
| **Pingtung** | 國立屏東科技大學 National Pingtung University of Science and Technology (NPUST) | 4 |
|  | 國立屏東大學 National Pingtung University (NPTU) | 3 |
|  | 大仁科技大學 Tajen University (TAJEN) | 2 |
|  | 美和科技大學 Meiho University (MU) | 1 |
| **Yunlin** | 國立虎尾科技大學 National Formosa University (NFU) | 2 |
|  | 佛光大學 Fo Guang University (FGU) | 2 |
|  | 國立雲林科技大學 National Yunlin University of Science and Technology (YunTech, NYUST) | 2 |
| **Miaoli** | 國立聯合大學 National United University (NUU) | 2 |
| **Kinmen** | 國立金門大學 National Quemoy University (NQU) | 2 |
| **Nantou** | 國立暨南國際大學 National Chi Nan University (NCNU) | 2 |
| **Yilan** | 國立宜蘭大學 National Ilan University (NIU) | 1 |

: Survey responses organized by county.

### Study Level
```{python}
#| label: fig-survey-study-level
#| fig-cap: "Study Level"
#| fig-scap: "Study Level"
student_counts()
```

### Age Distribution
```{python}
#| label: fig-survey-age-dist
#| fig-cap: "Age Distribution"
#| fig-scap: "Age Distribution"
student_age_ranking()
```

### University
```{python}
#| label: fig-survey-list-uni
#| fig-cap: "Universities"
#| fig-scap: "Universities"
university_ranking_table()
```

### Field of Study
Fields of study have not been normalized: there may be several expressions of the same academic department, written slightly differently.

```{python}
#| label: fig-survey-field-of-study
#| fig-cap: "Field of Study"
#| fig-scap: "Field of Study"
field_of_study_ranking()
```

### Personality Type

```{python}
#| label: fig-survey-mbti
#| fig-cap: "Personality Type (MBTI)"
#| fig-scap: "Personality Type (MBTI)"
mbti_ranking()
```


### Split Personas by MBTI Introversion vs Extroversion

```{python}
#| label: fig-survey-mbti-intro-vs-extro
#| fig-cap: "Split Personas by MBTI Introversion vs Extroversion (MBTI)"
#| fig-scap: "Split Personas by MBTI Introversion vs Extroversion (MBTI)"
mbti_introverts_vs_extroverts()
```

| Cluster Type        | % of Extroverts   | % of Introverts   | Description                               |
| ------------------- | ----------------- | ----------------- | ----------------------------------------- |
| High eco-engagement | \~37% (Cluster 0) | \~33% (Cluster 2) | Strong sustainability, AI use, confidence |
| Moderate            | \~33% (Cluster 2) | \~45% (Cluster 1) | Interested but not deeply involved        |
| Low engagement      | \~30% (Cluster 1) | \~22% (Cluster 0) | Low scores across eco, AI, finance        |

Introverted clusters generally show:

Slightly higher eco-anxiety and concern for climate change

More interest in practicing low-carbon lifestyles and doing more for the environment

Greater openness to new ideas

Extroverted clusters show:

More optimistic or neutral views on economic-environment tradeoffs

Slightly stronger trust in certifications and engagement with practical topics like buying property/car

More self-confidence in financial knowledge and actions


