```{=mdx}
import MyEmbed from '/src/components/Embed'
import Figure from '/src/components/Figure'
```

```{python}
from data.discussion import app_installs
import warnings
warnings.filterwarnings("ignore")
```

## Prototype Development

The interactive prototype is publicy available at the Google Chrome extensions store and separately at the website:
https://ai.ziran.tw/

### Prototype architecture

- Google Chrome browser extension 
- API microservice
- Ziran AI
- AI backend
- Ratings API
- Redis testing AI results
- Redis Page cache / from page / separate scraping service
- Documentation: GreenFilter: thesis website / github
- AI API got / Claude
- Stock ratings API
- Community ratings API

70 Questions
- Use report ID to do anonymous testing
- Page tracking to track the usage
- 7 app questions
- 63 personality questions

Other Tools Used: 
- QR generator in Canva
- Postman for API testing

### Google Chrome Extentsion App Installs

While Google is the most popular browser with over 3.45 billion users [@GoogleChromeStatistics2023], extensions are a relatively less known feature of the browser. Most popular extensions are Grammarly, for Taiwanese students End Note is familiar. However, it's only available for computers (extensions don't run on phones and tablets).

```{python}
#| label: fig-app-installs
#| fig-cap: "Green Filter Google Chrome Extension Installs"
#| fig-scap: "Green Filter Google Chrome Extension Installs"
app_installs()
```